(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 788,
	height: 383,
	fps: 24,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



(lib._1_Símbolo2 = function() {
	this.initialize();

	// Camada 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#66CCCC").s().p("Ag4ODQgYgYAAgiIAA6RQAAgiAYgYQAXgYAhABQAhgBAYAYQAYAYAAAiIAAaRQAAAigYAYQgYAYghAAQghAAgXgYg");
	this.shape.setTransform(798.2,544.6,1,2.083);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#66CCCC").s().p("AC4D8IiLgjIG9h4IvekeQhngLg1ANIAAheIADAAQAbgDAfABQAbAAAcADIAnAGIAYAEIPcEbQCHAiAKAmQAJAlhsApIlxB5g");
	this.shape_1.setTransform(651.4,91.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#66CCCC").s().p("Ag4ODQgYgYAAgiIAA6RQAAgiAYgYQAXgYAhABQAhgBAYAYQAYAYAAAiIAAaRQAAAigYAYQgYAYghAAQghAAgXgYg");
	this.shape_2.setTransform(899.3,248.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ah1QdIglgJIgJgCIAA5wQgjgKgbgLIHDmyIjYHoQgsgGgqgHIAAZwIgpgJg");
	this.shape_3.setTransform(780.9,85.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#A8A8A8").s().p("AmyO9IAA1IIAAhjIAAjHQAAgHACgGQANgoBSgsIG0kFIFQHQQiSAijIAAIgwAAIg6gCQgzgDgvgFIDWnoInCGyQAaALAkAKIAAZwQiPgogCg3g");
	this.shape_4.setTransform(793.5,84.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#999999").s().p("AjfH7IAAvHQBWAJBKAAQBrAABVgVQAzgNArgVIAAPEIgcAIQiaApjXAAIgxAAg");
	this.shape_5.setTransform(820.1,143.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#B6B6B6").s().p("AkAAoIAAgiQEsAdCShHIAWgMIAtAEIgFADQgTAOgVAMIgWALQgrATg0ANQhVAVhqAAQhKAAhWgJg");
	this.shape_6.setTransform(823.5,93.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#4F9F9F").s().p("AjqB9IAAjXIA0AAQDSAACWgeQAggGAZgGIAADJIgXAMQhpA0i3AAQhJAAhVgIg");
	this.shape_7.setTransform(821.2,81.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#CCCCCC").s().p("Al7NFIAA5vQAqAHAuAFQAvAFAzADIA8ACIAADnIAADIIAADZIAAAiIAAPHQiJgEhtgUgAFPjEIAAjLIAAh1IAAlIQAWgIASgIIAFKcg");
	this.shape_8.setTransform(811.2,107.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.lf(["#363636","#999999"],[0.212,1],25.8,21.1,-25.8,16.7).s().p("ACyCWQiWgdjSAAIg0ABIAAjkIAxAAQDFAACSgiIAagHQAbgHAYgIIAAFFQgZgHgggGg");
	this.shape_9.setTransform(821.2,39.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#666666").s().p("ACEBTIAWgLQAVgMATgOIAFgDIgFqaQgSAIgWAIQgXAJgcAHIgZAGIlOnPIHvFAIAIAKQAKANAAAOIAAABIAAACIgBZqQAAgBAAABQABAAAAAAQAAABAAABQAAABAAABQAAA0h9Ang");
	this.shape_10.setTransform(829.3,84.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#66CCCC").s().p("Aj+KmIinguIAAgBIphiqQgLgYAGgTQAKggA+gSIIeCSIAAgHIDMA3IAAzhIAcgVIEYAtIAABjIi8gjIgCT0QACAogtAAQgmAAhKgfgAI4kkIAAjJIA0AAQDUAACWAdQAfAGAZAHIAAB1QgZAGgfAGQiWAejUAAIg0AAg");
	this.shape_11.setTransform(740.8,101.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#666666").s().p("AgBgBQABAAADABQAAAAgBAAQAAAAAAAAQAAABgBAAQAAABgBAAQgCgBABgCg");
	this.shape_12.setTransform(516.4,46.6,0.949,0.949);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#666666").s().p("AgBgBQABAAACABQAAAAAAAAQAAAAAAAAQAAABgBAAQAAABgBAAQgCgBABgCg");
	this.shape_13.setTransform(521.8,49,0.949,0.949);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#666666").s().p("AgBgBQABAAACABQAAAAAAAAQAAAAAAAAQAAABgBAAQAAABgBAAQgCgBABgCg");
	this.shape_14.setTransform(520.9,48.5,0.949,0.949);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#666666").s().p("AgBgBQABAAADABQAAAAgBAAQAAAAAAAAQAAABgBAAQAAABgBAAQgCgBABgCg");
	this.shape_15.setTransform(522.8,48.5,0.949,0.949);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#666666").s().p("AgBgBQABAAACABQAAAAAAAAQAAAAAAAAQAAABgBAAQAAABgBAAQgBgCAAgBg");
	this.shape_16.setTransform(528.5,52.5,0.949,0.949);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#666666").s().p("AgCgBQACAAADABQAAAAgBAAQAAAAAAAAQAAABgBAAQAAABgBAAQgBgCgBgBg");
	this.shape_17.setTransform(523.7,53.5,0.949,0.949);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#666666").s().p("AgBgBQABAAACABQAAAAAAAAQAAAAAAAAQAAABgBAAQAAABgBAAQgCgBABgCg");
	this.shape_18.setTransform(525.1,53.3,0.949,0.949);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#666666").s().p("AgCgBQACAAADABQAAAAgBAAQAAAAAAAAQAAABgBAAQAAABgBAAQgBgCgBgBg");
	this.shape_19.setTransform(521.6,55.9,0.949,0.949);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#666666").s().p("AgBgBQABAAACABQAAAAAAAAQAAAAAAAAQAAABgBAAQAAABgBAAQgBgCAAgBg");
	this.shape_20.setTransform(547.7,55.6,0.949,0.949);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#666666").s().p("AgBgBQABAAACABQAAAAAAAAQAAAAAAAAQAAABgBAAQAAABgBAAQgCgCABgBg");
	this.shape_21.setTransform(515.4,46.1,0.949,0.949);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#666666").s().p("AgBgBQABAAACABQAAAAAAAAQAAAAAAAAQAAABgBAAQAAABgBAAQgCgCABgBg");
	this.shape_22.setTransform(524,52.3,0.949,0.949);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#666666").s().p("AgDAAQADgCAEACQAAAAAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQgEAAAAgCg");
	this.shape_23.setTransform(524.3,57.5,0.949,0.949);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#666666").s().p("AgCgBQACAAADABQAAAAgBAAQAAAAAAAAQAAABgBAAQAAABgBAAQgBgBgBgCg");
	this.shape_24.setTransform(532,61.6,0.949,0.949);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#666666").s().p("AgCgBQACAAADABQAAAAgBAAQAAAAAAAAQAAABgBAAQAAABgBAAQgBgCgBgBg");
	this.shape_25.setTransform(529.9,56.8,0.949,0.949);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#666666").s().p("AgCgBQACAAACABQAAAAAAAAQAAAAAAAAQAAABgBAAQAAABgBAAQgCgCAAgBg");
	this.shape_26.setTransform(537.2,53.7,0.949,0.949);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#666666").s().p("AgBgBQABAAACABQAAAAAAAAQAAAAAAAAQAAABgBAAQAAABgBAAQgCgBABgCg");
	this.shape_27.setTransform(515.4,59.4,0.949,0.949);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f().s("#999999").ss(1,1,1).p("ACPBkIA5gPIA8gPIA4gPIA+gRIDTg0IoWiLIqDClIF2BiICIAjIAOAJIAKgDIBJgTIA4gOg");
	this.shape_28.setTransform(70.9,51.9);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#B6B6B6").s().p("AAaCSIjWiIIgwARIBAAsIBAAoIl3hiIKDikIFEC/Ig/AQIj8idIgwARIBAAsIC0BvIg8APIj5ibIgvASIA/ArICxBtIhEASIj1iaIgvARIA/AqICtBtIhMATg");
	this.shape_29.setTransform(60.3,51.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#959595").s().p("AvND8ICCghICCAhIiEAigEAg4ACOICCgiIABAAICBAhIiEAjgEgk7gERIAogMIAAAJIAcAGIgcAHg");
	this.shape_30.setTransform(375,113.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.lf(["#CCCC99","#83836D"],[0,0.898],-49.1,0,49.1,0).s().p("ABhCDIpKi6IFKhQIACgCIKHCyIlzBhgAgmApQABAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAAAQgCgCgDAAQgBAEAEABgAAfAUQABgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAAAQgCgCgDAAQAAADADACgAhMAUQABgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAAAQgCgCgDAAQAAADADACgAgkASQABgBAAAAQABAAAAgBQAAAAAAgBQABAAAAgBQgCgBgEAAQAAADADACgAAyAPQABAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAAAQgCgCgDAAQAAAEADABgAAxgKQAAAAAAABQAAAAABABQAAAAABABQABAAAAAAIADAAQABAAAAAAQABAAAAAAQAAgBAAAAQAAgBABgBIgGgBIAAAAIgDABgAjcgOQAAAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAAAIgFgBQAAADAEABgAiigeQABgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQgDgBgDAAQAAADADACgAAfgjQABgBAAAAQABAAAAAAQAAgBAAAAQAAgBAAAAQgCgCgDAAQAAAEADABgAhfgjQABgBAAAAQABAAAAAAQAAgBAAAAQAAgBAAAAQgCgCgEAAQAAAEAEABgAgUguQAAAEAGAAQAAAAABAAQAAgBAAAAQABAAAAgBQAAgBAAAAIgFgCIgDABgAghgtQAAAAABAAQAAgBAAAAQABAAAAgBQAAAAAAgBQgCgBgEAAQAAADAEABgAj3gxQABgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBQgCgBgDAAQAAADADACgAgOg0QAAAAABAAQAAgBAAAAQABgBAAAAQAAAAAAgBQgDgBgDAAQABADADABgAAYg4QABgBAAAAQABAAAAgBQAAAAAAgBQABAAAAgBQgDgBgDAAQgBADAEACgAhfg7QABAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAAAQgCgCgEAAQAAAEAEABgAlPg7QABAAABgBQAAAAAAAAQABgBAAAAQAAgBAAAAQgCgCgEAAQAAAEADABgAiAg9QABgBAAAAQAAAAABgBQAAAAAAAAQAAgBAAAAQgCgCgDAAQgBADAEACgAgOhLQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQgDgBgDAAQABADADACgAi4hUQABAEAFAAQABAAAAAAQABgBAAAAQAAAAAAgBQABAAAAgBIgGgCIgDABgAhdhSQABgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQgDgBgDAAQAAADADACgAkPhVQABAAABgBQAAAAAAAAQABgBAAAAQAAgBAAAAQgCgCgEAAQAAAEADABgAiRheQABgBAAAAQABAAAAgBQAAAAAAgBQABAAAAgBQgDgBgDAAQAAADADACgAhThjQABgBAAAAQABAAAAgBQAAAAAAAAQAAgBAAAAQgCgCgDAAQgBADAEACgAiih0QABAAABgBQAAAAAAAAQABgBAAAAQAAgBAAAAIgGgBQAAADADABg");
	this.shape_31.setTransform(509.5,51.9);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#878787").s().p("AgDBmIhaAAIgGAzIAAlGQBaAGBUAAIAUAAIAFFUIguABIg/AAg");
	this.shape_32.setTransform(802.1,352.8);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#4F9F9F").s().p("AgJA8QhfAAhlgHQg6gFg9gGIgEhdQCEALCdAAQDMAACkgTIAABeQidAZiuAAIgHAAg");
	this.shape_33.setTransform(812.7,327.8);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#AAAAAA").s().p("AhZEEIheovQBpAUB6ALIgHAUIAIC+QA9AHA6AEIAUACIAAFGIgCASQilgHhqggg");
	this.shape_34.setTransform(773.6,340);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#333333").s().p("AgWB5Qh/AAhwAHIA4ilIAQgJICOhVIDpBiIABAAIBLClQiDgLiZAAg");
	this.shape_35.setTransform(811,283.8);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#CCCCCC").s().p("EA5BAXpQhWAAhagGIgUgCQg6gEg9gHIgIi+IAGgUQh7gLhqgTIgtgJQhAgNgugPQhggfgZglIgFgfQBriKE2h2IAAAFQAAAjB2AZQAvAKA3AGIABAAIAMABIgRAJIg3CoIg2CjIAEBfIAEBfQA8AHA7AEQBlAIBfAAQCzAAChgZIAAAQQigAci0ABIgUAAgEA8dAOpIAAAAIA2gKQB2gZAAgjQAAgFgCgFQEhBuBlB3QAGAGADAGIADAEQAGAKgBALQABALgGALIgCACQgDAHgIAHQgcAchKAZQgxAQhFAPQhYAShjAMgEgjSgEmIAAkTILPC6IAAETgAMzmUIAAkTILPC6IAAETgAtrpwICJgoIADgDQAOgPAAgVQAAgKgEgJQgDgJgHgIQgNgPgegHQgegIgKAHQgKAIgQADIjkBEIh/gmIACmqIAmAMIAMAEQHBCHHSCEIACGrgA4EnoIgCjqIJGCXInDB0gEg2dgKlIkQhVIgBgBIhkhEIpMmtIAAgxIAYgGIJLCYIgXAFIM+DXIAAGBgAYCpXIgDjqIJGCXInDB1gAoFvzIgGj8ILsDbInAB2gEgvNgPZIAAgJIAAlcILOC5IqyCzgAAMyQIAAjKIKKDHIAUAHIlXBagEg9wgS/IhAgoIgQg9IDYCIgEg8zgUWIgQg9ID2CcIg4AOgEg66gU4IgQg9ID6CdIg5APgEg5JgVYIgQg9ID9CfIg4APgAHo24IgCADIAAgyIAAAAIABgBIABAAILcDOIhSAWgEg5hgXHIIWCKIjTA3g");
	this.shape_36.setTransform(444.7,184.6);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#999999").s().p("EA5OAToQg3gGgvgKQh2gZAAgjIAAgEIABgBIACgEQAOgeBlgVQB1gZCmAAQCmAAB1AZQBlAVAOAdQADAFAAAFQAAAjh2AZIg2AKIjrhhIivBngEggHgD/IB6ggICvgtIGlhsIFlBeIDmA5ICDAiIrOC6gA+CkCIHGB1ICBAiICDgiIHDh1IpHiXgAP+luILOi5ILOC6IrOC5gASDlxIHGB2ICBAhICDgiIHDh0IpGiXgAuwsyIgMgDIgmgMIaUmmIOXEFI5mG7QnTiEnAiHgAsXtAIHdCHIEmBUIHAh2IrtjaIgBAAgAFAxTIABABIoTCBIGpB6IFGBeIFYhaIBUgWIF0hhIBRgWIrbjOIgBAAIgBAAIAAAAgEg5HgNMIAWgFIpLiZIgXgGILai9IJjCfIBMgUIM+DWIs9DXgEg3QgNMIKmCwIAoAKIAcgHIKyiyIrOi6gEhAcgPnIF3BhICIAkIANAIIAKgCIBMgTIA4gPIBEgSIA4gOIA8gQIA4gOIA/gRIDTg2IoXiLgADXwhIBqgYIAbAIQAXAAASgFIgeAKIJNC8IhUAXg");
	this.shape_37.setTransform(424.4,153.2);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#666666").s().p("EA2hAU9QC0AACggcIAAgRIAAhgIAAg5IhUi+IhLioIgBAAIjrhhIiOBVIgMgBICuhoIDsBhIAAAAICXFTQBkgMBXgTQBGgOAxgQQBKgZAcgdQAHgGAEgHIg6DoIgVAAIgZC5IgdB1IABAGIAAABQAAAPgYAdQgZAdirAuQhLAUhiALQhrANiFADgEAu9AZnQh4gmgzgfQgQgKgJgKIiho8QAZAlBfAeQAvAPA/ANIAuAJIBeIxIgNgEgA63oqILNi5IAAESIrNC6gAVOqZILNi5IAAETIgMADIj1hCQg/ASgJAhQgHATALAYIBkAcInsB/gAmbwLIZmm8IAAGrI5kG7gEgkBgLnIJHiWIACDqIiCAhgEgyIgRaIM9jXIAAF+Ih1AhIjZg6QgIgEgJgBQgSAAgNAPQgNAPgBAVIAAAAQABAWANAOIADADIBOAVIoQCJgAMEtWIJHiWIADDqIgBAAIiCAigEg9OgUxILOi4IAAFcIgoAMgAyW0lIHVh1IACAAIAHD8gAHi0+IBTgXIAWAHIhVAXgApQ21IIViCIgBgBIFvhbIAAAzIlIBPIAbgKQgPAFgXABIgbgJIhrAZIAADJgEhCjgW+IAvgRIAQA8gAGp2zQADgBACACQAAAAAAABQAAAAAAABQAAAAgBABQAAAAgBAAQgEgBABgDgEhAngXtIAwgSIAQA9gAHw3JQADAAACACQAAAAAAABQAAAAAAAAQAAABgBAAQAAABgBAAQgDgBAAgEgAGD3JQADAAACACQAAAAAAABQAAAAAAAAQAAABgBAAQAAABgBAAQgDgBAAgEgAGr3LQAEAAACABQAAABgBAAQAAABAAAAQAAABgBAAQAAABgBAAQgDgCAAgDgAID3NQADgBACACQAAABAAAAQAAAAAAABQAAAAgBABQAAAAgBAAQgDgBAAgDgAII3gQAAgBgBAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAAAABgBQAAAAABAAQAAAAABAAQAAAAAAAAIAFABQAAABAAABQAAAAAAABQAAAAgBAAQAAABgBAAIgDAAgEg+sgYOIAvgSIAQA9gADy3sIAFABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgEgBAAgDgAEt39QADAAADACQAAAAAAAAQAAABgBAAQAAABAAAAQgBABgBAAQgDgCAAgDgAHw4CQADABACABQAAABAAAAQAAAAAAABQAAAAgBAAQAAABgBAAQgDgBAAgEgAFv4CQAEABACABQAAABAAAAQAAAAAAABQAAAAgBAAQAAABgBAAQgEgBAAgEgEg88gYvIAvgSIAQA+gAG+4IQACgCAGADQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAAAQgGAAAAgEgAGt4LQAEAAACABQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQgEgCAAgDgADY4QQADAAACACQAAAAAAAAQAAABAAAAQAAABgBAAQAAABgBAAQgDgCAAgDgAHA4SQADAAADABQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAABQgDgCgBgDgAHp4XQADAAADACQAAAAgBAAQAAABAAAAQAAABgBAAQAAABgBAAQgEgCABgDgAFv4aQAEAAACACQAAAAAAABQAAAAAAABQAAAAgBABQAAAAgBAAQgEgBAAgEgACA4aQAEAAACACQAAAAAAABQAAAAgBABQAAAAAAABQgBAAgBAAQgDgBAAgEgAFP4cQADABACABQAAAAAAABQAAAAAAAAQgBABAAAAQAAABgBAAQgEgCABgDgAHA4qQADAAADACQAAAAAAAAQAAABgBAAQAAABAAAAQgBABAAAAQgDgCgBgDgAEa4uQACgCAHADQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBAAQgFAAgBgEgAFy4xQADAAADACQAAAAAAAAQAAABgBAAQAAABAAAAQgBABgBAAQgDgBAAgEgADA4zQAEAAACABQAAAAAAABQAAAAgBABQAAAAAAABQgBAAgBAAQgDgBAAgDgAE+49QADAAADACQAAAAgBAAQAAABAAAAQAAABgBAAQAAABgBAAQgDgCAAgDgAF85CQADABACABQAAAAAAABQAAAAAAABQAAAAgBAAQAAABgBAAQgEgCABgDgAEt5SIAGABQAAABAAAAQAAAAgBABQAAAAAAABQgBAAgBABQgDgCAAgDg");
	this.shape_38.setTransform(462.7,201.7);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#66CCCC").s().p("EA0FAShIAAAAIAZi5IAVAAIDcAAIAAC5gEAkrAPoIgEhfIA2ijQBwgIB/AAQCbAACDALIBUC+IAAA5QijAUjPAAQicAAiFgMgEAuYgKTIJHABIgyBXIgkAnIAAAKInxACgEg2vgQyIhOgUIgDgDQgNgPgBgVIAAgBQABgVANgOQANgPASAAQAJAAAIAEIDZA7IFkBhIiwAtgEgiKgQPIBvgXIDlhEQAQgDAKgIQAJgHAeAIQAeAHAOAPQAGAIAEAJQADAJAAAKQAAAVgNAPIgDADIiKAoIhNAWg");
	this.shape_39.setTransform(545,222.5);

	this.addChild(this.shape_39,this.shape_38,this.shape_37,this.shape_36,this.shape_35,this.shape_34,this.shape_33,this.shape_32,this.shape_31,this.shape_30,this.shape_29,this.shape_28,this.shape_27,this.shape_26,this.shape_25,this.shape_24,this.shape_23,this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,-20.7,907.5,757.7);


(lib._1_jato = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#66CCCC").s().p("AEHDBQlajuncggIAAhyQIZAUHrDbQAuATAsAWIAABog");
	this.shape.setTransform(56,25.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#7BF7F7").s().p("AHVCEQnrjaoZgVIAAhBQIdAYHwDhQAnASAlATIAFgQIAABLQgsgWgugTg");
	this.shape_1.setTransform(56,17.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#66CCCC").s().p("AEHDEQlYjxnZgjIAAhzIASABIGhA2IIkCuIAkAQIATAIIANAGIAvAXIALAFIAABog");
	this.shape_2.setTransform(55.7,26);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#7BF7F7").s().p("AIgCrIgvgWIgNgGIgTgIIgkgRIokitImhg2IgNgBIgFAAIAAhBQIYAbHrDjIAUAKIA4AbIAGgNIAAADIAAA8IgBAKIgKgFg");
	this.shape_3.setTransform(55.7,17.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#66CCCC").s().p("AEHDHQlWj0nWgmIAAhzQIQAcHlDgIAPAGIA2AaIAIAEIAJAFIAABog");
	this.shape_4.setTransform(55.5,26.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#7BF7F7").s().p("AIdCvIgIgEIg2gaIgTgIQnhjdoNgdIgDAAIAAhBQITAfHnDlIATAJQAdAOAbAOIAGgLIAAACIAAA8IgBAJIgIgEg");
	this.shape_5.setTransform(55.5,17.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#66CCCC").s().p("AEHDJQlUj2nUgpIAAhyQIMAeHiDjIAfAOIA0AaIACABIAABng");
	this.shape_6.setTransform(55.2,26.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#7BF7F7").s().p("AHsCcIgSgIIgSgJQndjgoIgeIgEgCIAAhAQIPAiHiDnIATAJIA3AcIAHgJIABADIAAA8IgCAHg");
	this.shape_7.setTransform(55.2,17.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#66CCCC").s().p("AEGDMQlRj5nRgsIAAhyQIIAhHdDmIAMAFIADABIASAJIAwAYIADACIAABng");
	this.shape_8.setTransform(54.9,26.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#7BF7F7").s().p("AHqChIgSgJIgDgCIgSgJQnZjioDghIgDgCIAAg/QIJAkHeDpIATAKIA3AcIAHgHIABADIAAA7IgDAGIgwgYg");
	this.shape_9.setTransform(54.9,18);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#66CCCC").s().p("AEHDPQlQj8nPgvIAAhyQIFAkHaDpQApATApAWIAABng");
	this.shape_10.setTransform(54.6,26.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#7BF7F7").s().p("AHRCZIgSgJQnVjkn/glIgDgCIAAg/QIFAnHaDsIATAJIA2AdIAIgFIABACIAAA7IgEAEIhEgig");
	this.shape_11.setTransform(54.6,18.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#66CCCC").s().p("AEGDSQlNkAnMgxIAAhzQIAAoHWDrQApAUAoAWIAABng");
	this.shape_12.setTransform(54.4,26.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#7BF7F7").s().p("AHMCcIgSgJQnRjnn6goIgCgCIAAg/QIAArHVDtIASAKQAcAOAaAPIAJgDIABACIAAA6IgEADIhEgig");
	this.shape_13.setTransform(54.4,18.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#7BF7F7").s().p("AHICeIgRgIIgBgBIgHgDIhmgxItIjeIgOgBIgCgDIAAg/QH8AuHRDwIASAJIA1AdIAKAAIABABIAAA7IgFABIhDgjg");
	this.shape_14.setTransform(54.1,18.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#66CCCC").s().p("AEHDVQlMkCnKg1IAAhyIAQABINIDeIBmAwIAHAEIABABIAKAEQAnAUAoAWIAABng");
	this.shape_15.setTransform(54.1,27);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#66CCCC").s().p("AEGDYQlJkFnHg4IAAhyQH4AtHPDxQAnAUAnAWIAABng");
	this.shape_16.setTransform(53.8,27.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#7BF7F7").s().p("AIFDDIhCgjIgSgJQnJjrnxgtIgBgEIAAg+QH2AxHNDyIASAKIA0AdIALABIABACIAAA6IgGgBg");
	this.shape_17.setTransform(53.8,18.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#66CCCC").s().p("AEGDbQlHkJnFg6IAAhyQH1AwHLD1QAnATAmAWIAABng");
	this.shape_18.setTransform(53.6,27.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#7BF7F7").s().p("AIADFIhCgjIgRgJQnFjuntgwIgBgEIAAg9QHyAzHID0IASAKIA0AdIALAEIACABIAAA6IgHgCg");
	this.shape_19.setTransform(53.6,18.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#7BF7F7").s().p("AH7DHIhCgkIgRgJIgcgPIuNkTIAAgFIAAg9QHtA3HED2IARAKQAaAOAaAPIALAGIACABIAAA6IgHgEg");
	this.shape_20.setTransform(53.3,18.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#66CCCC").s().p("AEGDeQlFkMnCg9IAAhyIAAAAIONETIArAYQAmATAlAWIAABng");
	this.shape_21.setTransform(53.3,27.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#66CCCC").s().p("AEGDhQlCkPnBhAIAAhyQHtA3HED6QAlATAlAVIAABog");
	this.shape_22.setTransform(53,27.6);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#7BF7F7").s().p("AG0ClQnEj6ntg3IAAhBQHyA7HHEBQAhASAhAUIAAA5QglgVglgUg");
	this.shape_23.setTransform(53,19.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#68D0D0").s().p("AGNDZIh/gFQlLkFm/g8IgFgvIAAg/IAAAAQHvAzHHD3IAkATIAlAVIACATIACARIAAANIgUA1IhhgEg");
	this.shape_24.setTransform(53.3,26.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#79F3F3").s().p("AIADNIgCgSIglgVIgkgTQnHj3nvg0IAAAAIAAg1IAAAAQHSAzGsDeIBJAnIAEACQAcATAcAWIAAAwIgBAIIgBgBg");
	this.shape_25.setTransform(53.3,19.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#77EFEF").s().p("AG4CtQhFgehHgaIgDgDIgBgCQlwjAmhgvIgdgLIAAhDQHZAwGyDdQAmAUAlAUIAEACQAZAVAaAXIAAAxIgBAEIgCAEIhMgig");
	this.shape_26.setTransform(53.6,20.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#6AD4D4").s().p("AGUDEIh+gJQlTj7m/g6IgKgpIAAgnIAdALQGhAvFwDAIABACIADADQBHAaBFAeIBMAiIACgEIABAIIgSA4IhhgHg");
	this.shape_27.setTransform(53.6,27);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#75EBEB").s().p("AIGDOIAFgSIAAAMIgDAHIgCgBgAIKC1IgKggIgmgVIgkgTQnMjun0gvIAAAAIAAgeIAAAAQHgAuG5DdQAlASAmAVIAEACIAtAwIAAAmIgBgHg");
	this.shape_28.setTransform(53.8,21.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#6CD8D8").s().p("AGbDIIh9gOQlbjxm/g2IgOglIAAhAIAAAAQH0AvHMDuIAkATIAmAUIAKAhIABAHIgFASIgLAnIhggLg");
	this.shape_29.setTransform(53.8,24.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#73E7E7").s().p("AIGDNIAKgpIAAAlIgEAGIgGgCgAIOCgIgNgdIAPAUIAAANIgCgEgAHbBtIglgSQnNjrn3gsIgBAAIAAgSIABAAQHmArHADcQAmATAnAVIAEACIAXAeIglgUg");
	this.shape_30.setTransform(54.1,22.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#6EDCDC").s().p("AGjC/Ih9gSQljjnm+gyIgUghIAAhAIABAAQH3ArHNDrIAlATIAlAUIABAAIAAABIANAeIACAEIgKAoIgEATIhfgPg");
	this.shape_31.setTransform(54.1,23.9);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#70E0E0").s().p("AgMgTIAIAEIAOAaIADABIgCAIIgXgng");
	this.shape_32.setTransform(106.3,35.7);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#71E3E3").s().p("AHnDDIg9gLIh9gXQlrjdm9gvIgYgdIAAhGIAAAAQHuAnHFDdQAnASAoAVIAEACIAHAMIAZApIABADIAAAzIgFAFIgogMg");
	this.shape_33.setTransform(54.4,22.9);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#70E0E0").s().p("AG+CfQhMgQhNgPIACgFIAAgBQlrjenEgqIgQgXIAAgMIAdAZQG9ArF0DSQA+ANA9APIBeAXIAGgnIAEAJIAAAzIgGAFIhVgTg");
	this.shape_34.setTransform(54.6,26.6);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#71E3E3").s().p("AGxCuQg9gOg+gNQl0jTm9grIgdgYIAAhBIABAAQH8AmHSDkIAlASIAnAUIATAbIADgCIgEAZIgGAnIhegXg");
	this.shape_35.setTransform(54.6,22);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#6EDCDC").s().p("AG/CoQhOgNhOgLIADgGIABgBQlqjknNgoIgMgbIAAgZIAhAUQG9AoF7DJQA+APA9ARIBdAbIADgYIAFAPIAAA1IgHACIhXgPg");
	this.shape_36.setTransform(54.9,26.7);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#73E7E7").s().p("AG4CmQg9gRg+gPQl7jJm9goIghgUIAAhBIABAAQH+AkHUDgIAlARIAnAUIAXAaIADgGIgFAsIgDAYIhdgbg");
	this.shape_37.setTransform(54.9,21.1);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#6CD8D8").s().p("AHBCyQhQgKhQgIIAFgHIABAAQlojsnWgmIgKgfIAAglIAmAQQG9AlGDC+QA+ARA9ATIBcAfIABgIIAFAVIAAA1IgIACIhZgLg");
	this.shape_38.setTransform(55.2,26.9);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#75EBEB").s().p("AHACdQg9gTg+gRQmDi/m9gkIgmgQIAAhBIACAAQIAAhHXDcIAlARIAnAUIAaAXIAEgHIgFA8IgBAJIhcgfg");
	this.shape_39.setTransform(55.2,20.2);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#6AD4D4").s().p("AHCC8QhRgHhSgFIAGgHIACgBQlnjznfglIgGghIAAgyIArAMQG8AgGLC1QA9AUA9AVQAtAQAtASIAFAkIAAA1IgJACIhbgIg");
	this.shape_40.setTransform(55.5,27);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#77EFEF").s().p("AIhC2QgtgRgtgQQg9gWg9gTQmLi1m8ggIgrgMIAAhBIABAAQIDAdHZDZIAlARIAoATIAdAWIAEgKIgDBHIgCgBg");
	this.shape_41.setTransform(55.5,19.3);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#79F3F3").s().p("AInCxIgCgRIgEgCQgqgVgqgSQnmjboQgYIgBAAIAAg1IACAAQIFAbHcDUIAlARIAoATIAgAUIAFgNIgCBJIgCgBg");
	this.shape_42.setTransform(55.7,18.3);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#68D0D0").s().p("AHEDLIingFIAIgHIABgBQllj7nogjIgDgkIAAhLIABAAQIQAZHmDaQAqASAqAWIAEABIACARIAEA7IAAA2IgKABIhdgFg");
	this.shape_43.setTransform(55.7,26.6);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#66CCCC").s().p("AEbDPIAJgHIACgBQljkCnyghIAAhyQIZAUHrDbQAuATAsAWIAACFg");
	this.shape_44.setTransform(56,27.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).to({state:[{t:this.shape_7},{t:this.shape_6}]},1).to({state:[{t:this.shape_9},{t:this.shape_8}]},1).to({state:[{t:this.shape_11},{t:this.shape_10}]},1).to({state:[{t:this.shape_13},{t:this.shape_12}]},1).to({state:[{t:this.shape_15},{t:this.shape_14}]},1).to({state:[{t:this.shape_17},{t:this.shape_16}]},1).to({state:[{t:this.shape_19},{t:this.shape_18}]},1).to({state:[{t:this.shape_21},{t:this.shape_20}]},1).to({state:[{t:this.shape_23},{t:this.shape_22}]},1).to({state:[{t:this.shape_25},{t:this.shape_24}]},1).to({state:[{t:this.shape_27},{t:this.shape_26}]},1).to({state:[{t:this.shape_29},{t:this.shape_28}]},1).to({state:[{t:this.shape_31},{t:this.shape_30}]},1).to({state:[{t:this.shape_33},{t:this.shape_32}]},1).to({state:[{t:this.shape_35},{t:this.shape_34}]},1).to({state:[{t:this.shape_37},{t:this.shape_36}]},1).to({state:[{t:this.shape_39},{t:this.shape_38}]},1).to({state:[{t:this.shape_41},{t:this.shape_40}]},1).to({state:[{t:this.shape_43},{t:this.shape_42}]},1).to({state:[{t:this.shape_1},{t:this.shape_44}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,112,45.2);


(lib._1_Interpolação4 = function() {
	this.initialize();

	// Camada 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,0,0,0.639)").s().p("EAa8Ao8QgQgjAAgyMAAAgmVQhrgFhIgWIgJgCQhUgbgkgWQgLgFgGgHIhxmRIgEgVQBLhhDahTIAAAAIABgDQALgVBGgOQBSgSB1AAQB0AABSASQBGAOALAVQDKBNBHBUQAEADADAFIACACQADAIAAAHQAAAIgDAHIgCACIgoCiIA6AAIAAwrIj+ABIAABBIAAADQAAAlhXAbIgVAFQhrAdiZAAIghAAQhggChNgOIgcgGIgagHIgGgBQhkgdgBgmIAAu0IiGgZIgBN6QACA1hvguIh1ghIAAgBIlrhkIlSBXIn1iDIAAjAIH1iCIGVBpIE2hUIq3jKQhJgHglAJIAAhCIACAAQATgCAWAAQATABAUACIAbAEIARADIK1DHQBfAYAHAbQAGAZhMAdIkCBVIAACrIgJADIisgvQgrANgHAWQgCADAAAEIABgDQAHgXAsgNIF7BmIAAgEICPAmIAAtsIAUgPIDGAfIAAiLQAAgFABgEQAJgdA5geIEzi3IFdDgIAFAHQAHAJAAALIAAAAIAAABIAAPeIEvAAIAIgBQAYAAAQARQARARAAAXIAAScQAAAYgRARIgBABIAAAQIi6AAIAAgBIgUBSIAAAEIAAABQAAALgRAUQgRATh4AfQg1AOhFAIQhLAKhdACIggAAIgJABMAAAAmSQAAAygRAjQgQAigYAAQgYAAgRgigEgj1gWNIAAjAIBWgXIk5hQQgdg/A8AAIGVBwIEmhNID6BCIBOgPIhZgbIACkrISdknIKCC2IAAErIx6E4InEiEIg2AQIBbAYIAADAIn2CCg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-253.1,-265.4,506.2,530.9);


(lib._1_Interpolação3 = function() {
	this.initialize();

	// Camada 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,0,0,0.639)").s("#FFFFFF").ss(1,1,1).rr(-374,-99,748,198,25.5);
	this.shape.setTransform(0,0,1.198,2.497);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-448.8,-248.2,897.8,496.4);


(lib._1_Interpolação2 = function() {
	this.initialize();

	// Camada 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EghxAFqIAAhyIAZAAIAAAKIABAAQABgFAFgEQAFgEAHAAQAOAAAHALQAGALAAAXIgBATQgBAJgDAGQgCAGgFADQgFAEgIAAQgGAAgFgDQgFgDgDgGIgBAAIAAAlgEghVAEPQgCAGAAANQAAAOACAHQABAHAGAAQAHAAABgGQACgHAAgNIAAgLIgBgJQgBgDgCgCQgCgDgEAAQgFAAgCAHgAzwFKQgIgGAAgNIAAgEIAXAAQABAGABAEQACAEAGAAQAFAAACgDQACgCAAgEQAAgEgCgCQgCgDgGgCIgOgFIgKgGQgDgDgCgEQgCgFAAgGQAAgNAIgHQAJgHAQAAQAJAAAGACQAGACAEAEQADADACAEQABAFAAAFIAAADIgXAAIAAgCQAAgFgCgCQgCgDgEAAQgFAAgCADQgCACAAADQAAAFADACIAMAEIAKAEIAIAEQAEADACAFQACAFAAAHQAAANgIAIQgJAIgQAAQgRAAgIgHgA02FNQgIgDgDgGQgEgGgBgIIgBgTQAAgKABgJQACgIADgGQAEgGAHgDQAHgEALAAQAMAAAHAEQAHADAEAGQADAGACAIIABATQAAAKgCAIQgBAJgEAGQgEAGgHADQgHAEgLAAQgLAAgHgEgA0rENQgDAGAAAQQAAAQADAGQACAHAFAAQAGAAACgGQACgGAAgRQAAgRgCgGQgCgGgGAAQgFAAgCAHgA5OFNQgHgEgDgHQgEgGgBgIIgBgUQAAgKACgHQABgIAEgGQAEgFAHgDQAHgEAKAAQAMAAAHAEQAHADADAHQAEAGABAJIABAVIgsAAIAAAGQAAAKACAFQACAFAFAAQAFAAACgEQACgEABgIIAYAAQAAAQgJAIQgJAIgQAAQgLAAgIgEgA4xEYQAAgKgCgEQgCgFgFAAQgGAAgCAFQgCAEAAAKIATAAIAAAAgA7KFKQgIgGAAgNIAAgEIAXAAQABAGABAEQACAEAGAAQAFAAACgDQACgCAAgEQAAgEgCgCQgCgDgGgCIgOgFIgKgGQgDgDgCgEQgCgFAAgGQAAgNAIgHQAJgHAQAAQAJAAAGACQAGACAEAEQADADACAEQABAFAAAFIAAADIgXAAIAAgCQAAgFgCgCQgCgDgEAAQgFAAgCADQgCACAAADQAAAFADACIAMAEIAKAEIAIAEQAEADACAFQACAFAAAHQAAANgIAIQgJAIgQAAQgRAAgIgHgA8bFKQgGgGAAgOQAAgHADgGQACgGAFgDIAIgDIAKgDIAFgBQAGgCACgBQACgCAAgFQAAgEgCgCQgCgDgFAAQgFAAgCADQgCADAAAGIgXAAQAAgIADgGQACgGAFgDQAEgDAGgBQAGgCAIAAQAQAAAHAGQAIAGAAAOIAAAtIAAALQABAFACACIgZAAIgCgKIAAAAQgDAGgFADQgGAEgGAAQgMAAgFgHgA8AEoIgEACQgEADAAAHQAAAFACADQACADADAAQAFAAACgDQADgDAAgGIABgKIAAgFIgKAEgA/xFKQgGgGAAgOQAAgHADgGQADgGAFgDIAHgDIAKgDIAGgBQAGgCABgBQACgCAAgFQAAgEgCgCQgCgDgEAAQgFAAgCADQgCADAAAGIgYAAQABgIACgGQADgGAEgDQAFgDAFgBQAGgCAIAAQARAAAHAGQAHAGAAAOIAAAtIABALQAAAFACACIgZAAIgBgKIgBAAQgCAGgGADQgFAEgHAAQgLAAgGgHgA/WEoIgEACQgEADAAAHQAAAFACADQACADAEAAQAEAAADgDQADgDAAgGIAAgKIAAgFIgKAEgA9CFOQgEgBgDgCQgCgCgCgFIgBgMIAAguIgKAAIAAgSIAKAAIAAgaIAaAAIAAAaIAMAAIAAASIgMAAIAAArQAAAFACACQACABAFAAIADAAIAAARIgPABIgLgBgAypFOIAAgdIAZAAIAAAdgA1mFOIgMgcIgMAcIgaAAIAXgtIgWgpIAaAAIAKAZIALgZIAaAAIgWApIAYAtgA26FOIAAhWIAaAAIAABWgA3kFOIAAhyIAaAAIAABygA95FOIAAg7QAAgKgIAAQgEAAgCADQgDAEAAAGIAAA4IgaAAIAAhWIAZAAIAAAKIAAAAQADgGAGgDQAFgEAHAAQALAAAGAGQAGAGAAAMIAABBgEggdAFOIAAhyIAaAAIAABygA26DvIAAgUIAaAAIAAAUgARCCpQgGgCgEgDQgEgEgBgEQgCgEAAgFIAYAAQABADACACQACACAEAAQAHAAACgFQACgFAAgMIAAgGIgBAAQgCAHgFADQgGADgHAAQgHAAgFgDQgEgDgDgGQgDgGgBgHIgBgRIAAgRQABgHADgHQADgGAFgEQAFgEAIAAQAIAAAFAEQAFAEACAGIABAAIAAgLIAYAAIAABTQAAAIgCAGQgCAGgEAEQgEAEgHACQgHADgKAAQgJAAgHgCgARLBOQgCAGAAAMQAAAOADAFQACAFAFAAQAFAAADgFQACgFAAgOQAAgNgCgFQgCgGgGAAQgGAAgCAGgApACpQgGgCgEgDQgEgEgBgEQgCgEAAgFIAYAAQABADACACQACACAEAAQAHAAACgFQACgFAAgMIAAgGIgBAAQgCAHgFADQgGADgHAAQgHAAgFgDQgEgDgDgGQgDgGgBgHIgBgRIAAgRQABgHADgHQADgGAFgEQAFgEAIAAQAIAAAFAEQAFAEACAGIABAAIAAgLIAYAAIAABTQAAAIgCAGQgCAGgEAEQgEAEgHACQgHADgKAAQgJAAgHgCgAo3BOQgCAGAAAMQAAAOADAFQACAFAFAAQAFAAADgFQACgFAAgOQAAgNgCgFQgCgGgGAAQgGAAgCAGgAZDCpIAAhyIAZAAIAAAKIABAAQABgFAFgEQAFgEAHAAQAOAAAHALQAGALAAAXIgBATQgBAJgDAGQgCAGgFADQgFAEgIAAQgGAAgFgDQgFgDgDgGIgBAAIAAAlgAZfBOQgCAGAAANQAAAOACAHQABAHAGAAQAHAAABgGQACgHAAgNIAAgLIgBgJQgBgDgCgCQgCgDgEAAQgFAAgCAHgAKqCpIAAhyIAZAAIAAAKIAAAAQACgFAFgEQAEgEAIAAQANAAAHALQAHALAAAXIgBATQgBAJgDAGQgDAGgFADQgFAEgHAAQgHAAgFgDQgFgDgDgGIAAAAIAAAlgALFBOQgCAGAAANQAAAOACAHQACAHAGAAQAGAAACgGQACgHAAgNIgBgLIgBgJQgBgDgCgCQgCgDgDAAQgGAAgCAHgABHCpIAAhyIAZAAIAAAKIABAAQABgFAFgEQAFgEAHAAQAOAAAHALQAGALAAAXIgBATQgBAJgDAGQgCAGgFADQgFAEgIAAQgGAAgFgDQgFgDgDgGIgBAAIAAAlgABjBOQgCAGAAANQAAAOACAHQABAHAGAAQAHAAABgGQACgHAAgNIAAgLIgBgJQgBgDgCgCQgCgDgEAAQgFAAgCAHgAtHCpIAAhyIAZAAIAAAKIAAAAQACgFAFgEQAEgEAIAAQANAAAHALQAHALAAAXIgBATQgBAJgDAGQgDAGgFADQgFAEgHAAQgHAAgFgDQgFgDgDgGIAAAAIAAAlgAssBOQgCAGAAANQAAAOACAHQACAHAGAAQAGAAACgGQACgHAAgNIgBgLIgBgJQgBgDgCgCQgCgDgDAAQgGAAgCAHgAfyCcQAFAAADgEQACgEAAgIIgKAAIAAgbIAZAAIAAAXIgBAMQgBAGgCAEQgDAEgFADQgFADgIAAgAqjCcQAFAAADgEQACgEAAgIIgKAAIAAgbIAZAAIAAAXIgBAMQgBAGgCAEQgDAEgFADQgFADgIAAgAesCJQgIgGAAgNIAAgEIAXAAQAAAGACAEQACAEAGAAQAEAAACgDQADgCAAgEQAAgEgCgCQgCgDgGgCIgPgFIgJgGQgEgDgCgEQgCgFAAgGQAAgNAJgHQAIgHAQAAQAJAAAGACQAGACAEAEQAEADABAEQACAFAAAFIAAADIgXAAIAAgCQAAgFgCgCQgCgDgFAAQgFAAgCADQgCACAAADQAAAFAEACIALAEIAKAEIAIAEQAEADACAFQADAFAAAHQAAANgJAIQgIAIgQAAQgRAAgIgHgAdnCMQgHgEgDgHQgEgGgBgIIgBgUQAAgKACgHQABgIAEgGQAEgFAHgDQAHgEAKAAQAMAAAHAEQAHADADAHQAEAGABAJIABAVIgsAAIAAAGQAAAKACAFQACAFAFAAQAFAAACgEQACgEABgIIAYAAQAAAQgJAIQgJAIgQAAQgLAAgIgEgAeEBXQAAgKgCgEQgCgFgFAAQgGAAgCAFQgCAEAAAKIATAAIAAAAgAakCMQgHgEgEgHQgDgGgBgIIgBgUQAAgKABgHQACgIAEgGQAEgFAHgDQAHgEAKAAQALAAAHAEQAHADAEAHQADAGABAJIABAVIgsAAIAAAGQAAAKADAFQABAFAGAAQAFAAACgEQACgEAAgIIAYAAQAAAQgJAIQgIAIgQAAQgMAAgHgEgAbABXQAAgKgCgEQgBgFgGAAQgGAAgBAFQgDAEAAAKIATAAIAAAAgAXaCMQgHgEgDgHQgEgGgBgIIgBgUQAAgKACgHQABgIAEgGQAEgFAHgDQAHgEAKAAQAMAAAHAEQAHADADAHQAEAGABAJIABAVIgsAAIAAAGQAAAKACAFQACAFAFAAQAFAAACgEQACgEABgIIAYAAQAAAQgJAIQgJAIgQAAQgLAAgIgEgAX3BXQAAgKgCgEQgCgFgFAAQgGAAgCAFQgCAEAAAKIATAAIAAAAgAV+CFQgGgLAAgXIABgUQABgIADgGQACgGAFgDQAFgEAIAAQAGAAAFADQAFADADAGIABAAIAAglIAaAAIAAByIgZAAIAAgKIgBAAQgBAFgFAEQgFAEgHAAQgOAAgHgLgAWUBNQgCAHAAANIAAALIABAJQABADACACQACADAEAAQAFAAACgHQACgGAAgNQAAgOgCgHQgBgHgGAAQgHAAgBAGgASRCMQgHgEgDgHQgEgGgBgIIgBgUQAAgKACgHQABgIAEgGQAEgFAHgDQAHgEAKAAQAMAAAHAEQAHADADAHQAEAGABAJIABAVIgsAAIAAAGQAAAKACAFQACAFAFAAQAFAAACgEQACgEABgIIAYAAQAAAQgJAIQgJAIgQAAQgLAAgIgEgASuBXQAAgKgCgEQgCgFgFAAQgGAAgCAFQgCAEAAAKIATAAIAAAAgAPkCJQgGgGAAgOQAAgHADgGQADgGAFgDIAHgDIAKgDIAGgBQAGgCABgBQACgCAAgFQAAgEgCgCQgCgDgEAAQgFAAgCADQgCADAAAGIgYAAQABgIACgGQADgGAEgDQAFgDAFgBQAGgCAIAAQARAAAHAGQAHAGAAAOIAAAtIABALQAAAFACACIgZAAIgBgKIgBAAQgCAGgGADQgFAEgHAAQgLAAgGgHgAP/BnIgEACQgEADAAAHQAAAFACADQACADAEAAQAEAAADgDQADgDAAgGIAAgKIAAgFIgKAEgAOcCJQgIgGAAgNIAAgEIAXAAQAAAGACAEQACAEAGAAQAEAAACgDQADgCAAgEQAAgEgCgCQgCgDgGgCIgPgFIgJgGQgEgDgCgEQgCgFAAgGQAAgNAJgHQAIgHAQAAQAJAAAGACQAGACAEAEQAEADABAEQACAFAAAFIAAADIgXAAIAAgCQAAgFgCgCQgCgDgFAAQgFAAgCADQgCACAAADQAAAFAEACIALAEIAKAEIAIAEQAEADACAFQADAFAAAHQAAANgJAIQgIAIgQAAQgRAAgIgHgANSCJQgIgGAAgNIAAgEIAXAAQAAAGACAEQACAEAGAAQAEAAACgDQADgCAAgEQAAgEgCgCQgCgDgGgCIgPgFIgJgGQgEgDgCgEQgCgFAAgGQAAgNAJgHQAIgHAQAAQAJAAAGACQAGACAEAEQAEADABAEQACAFAAAFIAAADIgXAAIAAgCQAAgFgCgCQgCgDgFAAQgFAAgCADQgCACAAADQAAAFAEACIALAEIAKAEIAIAEQAEADACAFQADAFAAAHQAAANgJAIQgIAIgQAAQgRAAgIgHgAMACJQgGgGAAgOQAAgHADgGQADgGAFgDIAHgDIAKgDIAGgBQAGgCABgBQACgCAAgFQAAgEgCgCQgCgDgEAAQgFAAgCADQgCADAAAGIgYAAQABgIACgGQADgGAEgDQAFgDAFgBQAGgCAIAAQARAAAHAGQAHAGAAAOIAAAtIABALQAAAFACACIgZAAIgBgKIgBAAQgCAGgGADQgFAEgHAAQgLAAgGgHgAMbBnIgEACQgEADAAAHQAAAFACADQACADAEAAQAEAAADgDQADgDAAgGIAAgKIAAgFIgKAEgAI0CJQgGgGAAgOQAAgHADgGQACgGAFgDIAIgDIAKgDIAFgBQAGgCACgBQACgCAAgFQAAgEgCgCQgCgDgFAAQgFAAgCADQgCADAAAGIgXAAQAAgIADgGQACgGAFgDQAEgDAGgBQAGgCAIAAQAQAAAHAGQAIAGAAAOIAAAtIAAALQABAFACACIgZAAIgCgKIAAAAQgDAGgFADQgGAEgGAAQgMAAgFgHgAJPBnIgEACQgEADAAAHQAAAFACADQACADADAAQAFAAACgDQADgDAAgGIABgKIAAgFIgKAEgAFICMQgHgEgEgHQgDgGgBgIIgBgUQAAgKABgHQACgIAEgGQAEgFAHgDQAHgEAKAAQALAAAHAEQAHADAEAHQADAGABAJIABAVIgsAAIAAAGQAAAKADAFQABAFAGAAQAFAAACgEQACgEAAgIIAYAAQAAAQgJAIQgIAIgQAAQgMAAgHgEgAFkBXQAAgKgCgEQgBgFgGAAQgGAAgBAFQgDAEAAAKIATAAIAAAAgADsCFQgHgLAAgXIABgUQABgIADgGQADgGAFgDQAFgEAHAAQAHAAAFADQAFADADAGIAAAAIAAglIAaAAIAAByIgZAAIAAgKIAAAAQgCAFgFAEQgEAEgIAAQgNAAgHgLgAEBBNQgCAHAAANIABALIABAJQABADACACQACADADAAQAGAAACgHQACgGAAgNQAAgOgCgHQgCgHgGAAQgGAAgCAGgACoCMQgHgEgEgHQgDgGgBgIIgBgUQAAgKABgHQACgIAEgGQAEgFAHgDQAHgEAKAAQALAAAHAEQAHADAEAHQADAGABAJIABAVIgsAAIAAAGQAAAKADAFQABAFAGAAQAFAAACgEQACgEAAgIIAYAAQAAAQgJAIQgIAIgQAAQgMAAgHgEgADEBXQAAgKgCgEQgBgFgGAAQgGAAgBAFQgDAEAAAKIATAAIAAAAgAjOCJQgIgGAAgNIAAgEIAXAAQAAAGACAEQACAEAGAAQAEAAACgDQADgCAAgEQAAgEgCgCQgCgDgGgCIgPgFIgJgGQgEgDgCgEQgCgFAAgGQAAgNAJgHQAIgHAQAAQAJAAAGACQAGACAEAEQAEADABAEQACAFAAAFIAAADIgXAAIAAgCQAAgFgCgCQgCgDgFAAQgFAAgCADQgCACAAADQAAAFAEACIALAEIAKAEIAIAEQAEADACAFQADAFAAAHQAAANgJAIQgIAIgQAAQgRAAgIgHgAkTCMQgHgEgDgHQgEgGgBgIIgBgUQAAgKACgHQABgIAEgGQAEgFAHgDQAHgEAKAAQAMAAAHAEQAHADADAHQAEAGABAJIABAVIgsAAIAAAGQAAAKACAFQACAFAFAAQAFAAACgEQACgEABgIIAYAAQAAAQgJAIQgJAIgQAAQgLAAgIgEgAj2BXQAAgKgCgEQgCgFgFAAQgGAAgCAFQgCAEAAAKIATAAIAAAAgAlvCFQgGgLAAgXIABgUQABgIADgGQACgGAFgDQAFgEAIAAQAGAAAFADQAFADADAGIABAAIAAglIAaAAIAAByIgZAAIAAgKIgBAAQgBAFgFAEQgFAEgHAAQgOAAgHgLgAlZBNQgCAHAAANIAAALIABAJQABADACACQACADAEAAQAFAAACgHQACgGAAgNQAAgOgCgHQgBgHgGAAQgHAAgBAGgAnACJQgGgGAAgOQAAgHADgGQADgGAFgDIAHgDIAKgDIAGgBQAGgCABgBQACgCAAgFQAAgEgCgCQgCgDgEAAQgFAAgCADQgCADAAAGIgYAAQABgIACgGQADgGAEgDQAFgDAFgBQAGgCAIAAQARAAAHAGQAHAGAAAOIAAAtIABALQAAAFACACIgZAAIgBgKIgBAAQgCAGgGADQgFAEgHAAQgLAAgGgHgAmlBnIgEACQgEADAAAHQAAAFACADQACADAEAAQAEAAADgDQADgDAAgGIAAgKIAAgFIgKAEgArxCJQgGgGAAgOQAAgHADgGQADgGAFgDIAHgDIAKgDIAGgBQAGgCABgBQACgCAAgFQAAgEgCgCQgCgDgEAAQgFAAgCADQgCADAAAGIgYAAQABgIACgGQADgGAEgDQAFgDAFgBQAGgCAIAAQARAAAHAGQAHAGAAAOIAAAtIABALQAAAFACACIgZAAIgBgKIgBAAQgCAGgGADQgFAEgHAAQgLAAgGgHgArWBnIgEACQgEADAAAHQAAAFACADQACADAEAAQAEAAADgDQADgDAAgGIAAgKIAAgFIgKAEgAuUCJQgGgGAAgOQAAgHADgGQADgGAFgDIAHgDIAKgDIAGgBQAGgCABgBQACgCAAgFQAAgEgCgCQgCgDgEAAQgFAAgCADQgCADAAAGIgYAAQABgIACgGQADgGAEgDQAFgDAFgBQAGgCAIAAQARAAAHAGQAHAGAAAOIAAAtIABALQAAAFACACIgZAAIgBgKIgBAAQgCAGgGADQgFAEgHAAQgLAAgGgHgAt5BnIgEACQgEADAAAHQAAAFACADQACADAEAAQAEAAADgDQADgDAAgGIAAgKIAAgFIgKAEgAwJCMQgHgEgEgHQgDgGgBgIIgBgUQAAgKABgHQACgIAEgGQAEgFAHgDQAHgEAKAAQALAAAHAEQAHADAEAHQADAGABAJIABAVIgsAAIAAAGQAAAKADAFQABAFAGAAQAFAAACgEQACgEAAgIIAYAAQAAAQgJAIQgIAIgQAAQgMAAgHgEgAvtBXQAAgKgCgEQgBgFgGAAQgGAAgBAFQgDAEAAAKIATAAIAAAAgAyNCJQgGgGAAgOQAAgHADgGQADgGAFgDIAHgDIAKgDIAGgBQAGgCABgBQACgCAAgFQAAgEgCgCQgCgDgEAAQgFAAgCADQgCADAAAGIgYAAQABgIACgGQADgGAEgDQAFgDAFgBQAGgCAIAAQARAAAHAGQAHAGAAAOIAAAtIABALQAAAFACACIgZAAIgBgKIgBAAQgCAGgGADQgFAEgHAAQgLAAgGgHgAxyBnIgEACQgEADAAAHQAAAFACADQACADAEAAQAEAAADgDQADgDAAgGIAAgKIAAgFIgKAEgAzVCJQgIgGAAgNIAAgEIAXAAQAAAGACAEQACAEAGAAQAEAAACgDQADgCAAgEQAAgEgCgCQgCgDgGgCIgPgFIgJgGQgEgDgCgEQgCgFAAgGQAAgNAJgHQAIgHAQAAQAJAAAGACQAGACAEAEQAEADABAEQACAFAAAFIAAADIgXAAIAAgCQAAgFgCgCQgCgDgFAAQgFAAgCADQgCACAAADQAAAFAEACIALAEIAKAEIAIAEQAEADACAFQADAFAAAHQAAANgJAIQgIAIgQAAQgRAAgIgHgA0fCJQgIgGAAgNIAAgEIAXAAQAAAGACAEQACAEAGAAQAEAAACgDQADgCAAgEQAAgEgCgCQgCgDgGgCIgPgFIgJgGQgEgDgCgEQgCgFAAgGQAAgNAJgHQAIgHAQAAQAJAAAGACQAGACAEAEQAEADABAEQACAFAAAFIAAADIgXAAIAAgCQAAgFgCgCQgCgDgFAAQgFAAgCADQgCACAAADQAAAFAEACIALAEIAKAEIAIAEQAEADACAFQADAFAAAHQAAANgJAIQgIAIgQAAQgRAAgIgHgA1kCMQgHgEgDgHQgEgGgBgIIgBgUQAAgKACgHQABgIAEgGQAEgFAHgDQAHgEAKAAQAMAAAHAEQAHADADAHQAEAGABAJIABAVIgsAAIAAAGQAAAKACAFQACAFAFAAQAFAAACgEQACgEABgIIAYAAQAAAQgJAIQgJAIgQAAQgLAAgIgEgA1HBXQAAgKgCgEQgCgFgFAAQgGAAgCAFQgCAEAAAKIATAAIAAAAgA5oCJQgIgGAAgNIAAgEIAXAAQAAAGACAEQACAEAGAAQAEAAACgDQADgCAAgEQAAgEgCgCQgCgDgGgCIgPgFIgJgGQgEgDgCgEQgCgFAAgGQAAgNAJgHQAIgHAQAAQAJAAAGACQAGACAEAEQAEADABAEQACAFAAAFIAAADIgXAAIAAgCQAAgFgCgCQgCgDgFAAQgFAAgCADQgCACAAADQAAAFAEACIALAEIAKAEIAIAEQAEADACAFQADAFAAAHQAAANgJAIQgIAIgQAAQgRAAgIgHgA66CJQgGgGAAgOQAAgHADgGQADgGAFgDIAHgDIAKgDIAGgBQAGgCABgBQACgCAAgFQAAgEgCgCQgCgDgEAAQgFAAgCADQgCADAAAGIgYAAQABgIACgGQADgGAEgDQAFgDAFgBQAGgCAIAAQARAAAHAGQAHAGAAAOIAAAtIABALQAAAFACACIgZAAIgBgKIgBAAQgCAGgGADQgFAEgHAAQgLAAgGgHgA6fBnIgEACQgEADAAAHQAAAFACADQACADAEAAQAEAAADgDQADgDAAgGIAAgKIAAgFIgKAEgA86CMQgHgDgEgGQgDgGgCgIIgBgTQAAgKACgJQABgIAEgGQAEgGAHgDQAHgEALAAQALAAAIAEQAHADADAGQAEAGABAIIABATQAAAKgBAIQgCAJgDAGQgEAGgHADQgHAEgLAAQgMAAgHgEgA8vBMQgCAGAAAQQAAAQACAGQACAHAGAAQAGAAACgGQACgGAAgRQAAgRgCgGQgCgGgGAAQgGAAgCAHgA/ICKQgGgGAAgMIAAhBIAaAAIAAA7QAAAKAIAAQAEAAADgDQACgEAAgGIAAg4IAaAAIAABWIgZAAIAAgKIAAAAQgDAGgFADQgGAEgHAAQgLAAgGgGgEggcACFQgHgLAAgXIABgUQABgIADgGQADgGAFgDQAFgEAHAAQAHAAAFADQAFADADAGIAAAAIAAglIAaAAIAAByIgZAAIAAgKIAAAAQgCAFgFAEQgEAEgIAAQgNAAgHgLgEggHABNQgCAHAAANIABALIABAJQABADACACQACADADAAQAGAAACgHQACgGAAgNQAAgOgCgHQgCgHgGAAQgGAAgCAGgEghtACJQgGgGAAgOQAAgHADgGQACgGAFgDIAIgDIAKgDIAFgBQAGgCACgBQACgCAAgFQAAgEgCgCQgCgDgFAAQgFAAgCADQgCADAAAGIgXAAQAAgIADgGQACgGAFgDQAEgDAGgBQAGgCAIAAQAQAAAHAGQAIAGAAAOIAAAtIAAALQABAFACACIgZAAIgCgKIAAAAQgDAGgFADQgGAEgGAAQgMAAgFgHgEghSABnIgEACQgEADAAAHQAAAFACADQACADADAAQAFAAACgDQADgDAAgGIABgKIAAgFIgKAEgAu7CNQgEgBgCgCQgDgCgBgFIgBgMIAAguIgLAAIAAgSIALAAIAAgaIAaAAIAAAaIAMAAIAAASIgMAAIAAArQAAAFACACQABABAFAAIAEAAIAAARIgPABIgMgBgA9sCNQgEgBgCgCQgDgCgBgFIgBgMIAAguIgLAAIAAgSIALAAIAAgaIAaAAIAAAaIAMAAIAAASIgMAAIAAArQAAAFACACQABABAFAAIAEAAIAAARIgPABIgMgBgAc4CNIgLgcIgNAcIgaAAIAYgtIgWgpIAaAAIAKAZIALgZIAaAAIgWApIAXAtgAbkCNIAAhWIAaAAIAABWgAUnCNIAAg7QAAgKgHAAQgEAAgDADQgDAEAAAGIAAA4IgaAAIAAg7QAAgKgHAAQgEAAgDADQgCAEAAAGIAAA4IgaAAIAAhWIAZAAIAAAKIAAAAQADgGAFgDQAGgEAHAAIAGABIAGACIAFAEIAEAHQAFgIAEgDQAFgDAIAAQALAAAFAGQAGAGAAAMIAABBgAHeCNIAAg7QAAgKgIAAQgEAAgCADQgDAEAAAGIAAA4IgaAAIAAg7QAAgKgIAAQgEAAgCADQgDAEAAAGIAAA4IgaAAIAAhWIAZAAIAAAKIABAAQACgGAGgDQAFgEAHAAIAHABIAGACIAFAEIAEAHQAEgIAFgDQAFgDAHAAQALAAAGAGQAGAGAAAMIAABBgAAeCNIAAg7QAAgKgHAAQgEAAgDADQgDAEAAAGIAAA4IgYAAIAAg7QAAgKgHAAQgEAAgDADQgCAEAAAGIAAA4IgaAAIAAhWIAZAAIAAAKIAAAAQADgGAFgDQAGgEAHAAIAGABIAEACIAFAEIAEAHQAFgIAEgDQAFgDAIAAQALAAAFAGQAGAGAAAMIAABBgAhfCNIAAhWIAaAAIAABWgAn+CNIAAhWIAZAAIAAAMIAAAAQADgHAFgEQAFgEAIAAIAEABIAAAYIgHgBQgIAAgFAEQgEAEAAAIIAAAxgA2fCNIgYhOIAABOIgYAAIAAhyIAfAAIAWBKIAAhKIAZAAIAABygA4iCNIAAgdIAZAAIAAAdgA74CNIAAhWIAZAAIAAAMIAAAAQADgHAFgEQAFgEAIAAIAEABIAAAYIgHgBQgIAAgFAEQgEAEAAAIIAAAxgAbkAuIAAgUIAaAAIAAAUgAhfAuIAAgUIAaAAIAAAUgAOggWQgHgCgDgDQgEgEgCgEQgBgEAAgFIAYAAQAAADACACQADACAEAAQAGAAACgFQACgFAAgMIAAgGIAAAAQgDAHgFADQgFADgIAAQgHAAgEgDQgFgDgDgGQgDgGgBgHIgBgRIABgRQABgHACgHQADgGAFgEQAFgEAIAAQAIAAAFAEQAFAEADAGIAAAAIAAgLIAYAAIAABTQAAAIgCAGQgCAGgEAEQgEAEgHACQgHADgKAAQgJAAgGgCgAOphxQgCAGAAAMQAAAOACAFQACAFAFAAQAGAAACgFQACgFAAgOQAAgNgCgFQgCgGgFAAQgGAAgCAGgAtHgWQgHgCgDgDQgEgEgCgEQgBgEAAgFIAYAAQAAADACACQADACAEAAQAGAAACgFQACgFAAgMIAAgGIAAAAQgDAHgFADQgFADgIAAQgHAAgEgDQgFgDgDgGQgDgGgBgHIgBgRIABgRQABgHACgHQADgGAFgEQAFgEAIAAQAIAAAFAEQAFAEADAGIAAAAIAAgLIAYAAIAABTQAAAIgCAGQgCAGgEAEQgEAEgHACQgHADgKAAQgJAAgGgCgAs+hxQgCAGAAAMQAAAOACAFQACAFAFAAQAGAAACgFQACgFAAgOQAAgNgCgFQgCgGgFAAQgGAAgCAGgEAg6gA2QgIgGAAgNIAAgEIAXAAQABAGABAEQACAEAGAAQAFAAACgDQACgCAAgEQAAgEgCgCQgCgDgGgCIgOgFIgKgGQgDgDgCgEQgCgFAAgGQAAgNAIgHQAJgHAQAAQAJAAAGACQAGACAEAEQADADACAEQABAFAAAFIAAADIgXAAIAAgCQAAgFgCgCQgCgDgEAAQgFAAgCADQgCACAAADQAAAFADACIAMAEIAKAEIAIAEQAEADACAFQACAFAAAHQAAANgIAIQgJAIgQAAQgRAAgIgHgAfpg2QgGgGAAgOQAAgHADgGQACgGAFgDIAIgDIAKgDIAFgBQAGgCACgBQACgCAAgFQAAgEgCgCQgCgDgFAAQgFAAgCADQgCADAAAGIgXAAQAAgIADgGQACgGAFgDQAEgDAGgBQAGgCAIAAQAQAAAHAGQAIAGAAAOIAAAtIAAALQABAFACACIgZAAIgCgKIAAAAQgDAGgFADQgGAEgGAAQgMAAgFgHgEAgEgBYIgEACQgEADAAAHQAAAFACADQACADADAAQAFAAACgDQADgDAAgGIABgKIAAgFIgKAEgAeXg6QgHgLAAgXIABgUQABgIADgGQADgGAFgDQAFgEAHAAQAHAAAFADQAFADADAGIAAAAIAAglIAaAAIAAByIgZAAIAAgKIAAAAQgCAFgFAEQgEAEgIAAQgNAAgHgLgAeshyQgCAHAAANIABALIABAJQABADACACQACADADAAQAGAAACgHQACgGAAgNQAAgOgCgHQgCgHgGAAQgGAAgCAGgAdGg2QgGgGAAgOQAAgHADgGQACgGAFgDIAIgDIAKgDIAFgBQAGgCACgBQACgCAAgFQAAgEgCgCQgCgDgFAAQgFAAgCADQgCADAAAGIgXAAQAAgIADgGQACgGAFgDQAEgDAGgBQAGgCAIAAQAQAAAHAGQAIAGAAAOIAAAtIAAALQABAFACACIgZAAIgCgKIAAAAQgDAGgFADQgGAEgGAAQgMAAgFgHgAdhhYIgEACQgEADAAAHQAAAFACADQACADADAAQAFAAACgDQADgDAAgGIABgKIAAgFIgKAEgAZ2g2QgGgGAAgOQAAgHADgGQADgGAFgDIAHgDIAKgDIAGgBQAGgCABgBQACgCAAgFQAAgEgCgCQgCgDgEAAQgFAAgCADQgCADAAAGIgYAAQABgIACgGQADgGAEgDQAFgDAFgBQAGgCAIAAQARAAAHAGQAHAGAAAOIAAAtIABALQAAAFACACIgZAAIgBgKIgBAAQgCAGgGADQgFAEgHAAQgLAAgGgHgAaRhYIgEACQgEADAAAHQAAAFACADQACADAEAAQAEAAADgDQADgDAAgGIAAgKIAAgFIgKAEgAXggzQgHgEgDgHQgEgGgBgIIgBgUQAAgKACgHQABgIAEgGQAEgFAHgDQAHgEAKAAQAKAAAHADQAHACADAFQAEAEACAHQACAGAAAIIgYAAQAAgJgDgEQgCgFgFAAQgGAAgCAHQgCAHAAAPQAAAQACAGQACAHAGAAQAFAAACgFQACgEABgMIAYAAQgBAUgIAJQgIAJgSAAQgLAAgIgEgAVkg2QgIgGAAgNIAAgEIAXAAQABAGABAEQACAEAGAAQAFAAACgDQACgCAAgEQAAgEgCgCQgCgDgGgCIgOgFIgKgGQgDgDgCgEQgCgFAAgGQAAgNAIgHQAJgHAQAAQAJAAAGACQAGACAEAEQADADACAEQABAFAAAFIAAADIgXAAIAAgCQAAgFgCgCQgCgDgEAAQgFAAgCADQgCACAAADQAAAFADACIAMAEIAKAEIAIAEQAEADACAFQACAFAAAHQAAANgIAIQgJAIgQAAQgRAAgIgHgAUggzQgHgEgEgHQgDgGgBgIIgBgUQAAgKABgHQACgIAEgGQAEgFAHgDQAHgEAKAAQALAAAHAEQAHADAEAHQADAGABAJIABAVIgsAAIAAAGQAAAKADAFQABAFAGAAQAFAAACgEQACgEAAgIIAYAAQAAAQgJAIQgIAIgQAAQgMAAgHgEgAU8hoQAAgKgCgEQgBgFgGAAQgGAAgBAFQgDAEAAAKIATAAIAAAAgATEg6QgHgLAAgXIABgUQABgIADgGQADgGAFgDQAFgEAHAAQAHAAAFADQAFADADAGIAAAAIAAglIAaAAIAAByIgZAAIAAgKIAAAAQgCAFgFAEQgEAEgIAAQgNAAgHgLgATZhyQgCAHAAANIABALIABAJQABADACACQACADADAAQAGAAACgHQACgGAAgNQAAgOgCgHQgCgHgGAAQgGAAgCAGgAQgg2QgGgGAAgOQAAgHADgGQACgGAFgDIAIgDIAKgDIAFgBQAGgCACgBQACgCAAgFQAAgEgCgCQgCgDgFAAQgFAAgCADQgCADAAAGIgXAAQAAgIADgGQACgGAFgDQAEgDAGgBQAGgCAIAAQAQAAAHAGQAIAGAAAOIAAAtIAAALQABAFACACIgZAAIgCgKIAAAAQgDAGgFADQgGAEgGAAQgMAAgFgHgAQ7hYIgEACQgEADAAAHQAAAFACADQACADADAAQAFAAACgDQADgDAAgGIABgKIAAgFIgKAEgAKmgzQgHgEgEgHQgDgGgBgIIgBgUQAAgKABgHQACgIAEgGQAEgFAHgDQAHgEAKAAQALAAAHAEQAHADAEAHQADAGABAJIABAVIgsAAIAAAGQAAAKADAFQABAFAGAAQAFAAACgEQACgEAAgIIAYAAQAAAQgJAIQgIAIgQAAQgMAAgHgEgALChoQAAgKgCgEQgBgFgGAAQgGAAgBAFQgDAEAAAKIATAAIAAAAgAJlgzQgFgEgBgFIgBAAIAAAKIgZAAIAAhyIAaAAIAAAlIABAAQADgGAFgDQAFgDAGAAQAIAAAFAEQAFADACAGQADAGABAIIABAUQAAAXgGALQgHALgOAAQgHAAgFgEgAJhhxQgCAHAAAOQAAANACAGQACAHAFAAQAEAAACgDQACgCABgEIABgIIAAgLQAAgNgCgHQgBgGgHAAQgGAAgBAHgAHXg2QgIgGAAgNIAAgEIAXAAQAAAGACAEQACAEAGAAQAEAAACgDQADgCAAgEQAAgEgCgCQgCgDgGgCIgPgFIgJgGQgEgDgCgEQgCgFAAgGQAAgNAJgHQAIgHAQAAQAJAAAGACQAGACAEAEQAEADABAEQACAFAAAFIAAADIgXAAIAAgCQAAgFgCgCQgCgDgFAAQgFAAgCADQgCACAAADQAAAFAEACIALAEIAKAEIAIAEQAEADACAFQADAFAAAHQAAANgJAIQgIAIgQAAQgRAAgIgHgAGQgzQgHgDgEgGQgDgGgCgIIgBgTQAAgKACgJQABgIAEgGQAEgGAHgDQAHgEALAAQALAAAIAEQAHADADAGQAEAGABAIIABATQAAAKgBAIQgCAJgDAGQgEAGgHADQgHAEgLAAQgMAAgHgEgAGbhzQgCAGAAAQQAAAQACAGQACAHAGAAQAGAAACgGQACgGAAgRQAAgRgCgGQgCgGgGAAQgGAAgCAHgAFPgzQgFgEgCgFIAAAAIAAAKIgZAAIAAhyIAaAAIAAAlIAAAAQADgGAFgDQAFgDAHAAQAHAAAFAEQAFADADAGQADAGABAIIABAUQAAAXgHALQgHALgNAAQgIAAgEgEgAFKhxQgCAHAAAOQAAANACAGQACAHAGAAQADAAACgDQACgCABgEIABgIIABgLQAAgNgCgHQgCgGgGAAQgGAAgCAHgADig1QgGgGAAgMIAAhBIAaAAIAAA7QAAAKAHAAQAEAAADgDQADgEAAgGIAAg4IAaAAIAABWIgZAAIAAgKIgBAAQgCAGgGADQgFAEgHAAQgMAAgFgGgABAgzQgHgEgDgHQgEgGgBgIIgBgUQAAgKACgHQABgIAEgGQAEgFAHgDQAHgEAKAAQAMAAAHAEQAHADADAHQAEAGABAJIABAVIgsAAIAAAGQAAAKACAFQACAFAFAAQAFAAACgEQACgEABgIIAYAAQAAAQgJAIQgJAIgQAAQgLAAgIgEgABdhoQAAgKgCgEQgCgFgFAAQgGAAgCAFQgCAEAAAKIATAAIAAAAgAgag6QgGgLAAgXIABgUQABgIADgGQACgGAFgDQAFgEAIAAQAGAAADADQAFADADAGIABAAIAAglIAaAAIAAByIgZAAIAAgKIgBAAQgBAFgFAEQgFAEgFAAQgOAAgHgLgAgEhyQgCAHAAANIAAALIABAJQABADACACQACADACAAQAFAAACgHQACgGAAgNQAAgOgCgHQgBgHgGAAQgFAAgBAGgAiNg2QgIgGAAgNIAAgEIAXAAQABAGABAEQACAEAGAAQAFAAACgDQACgCAAgEQAAgEgCgCQgCgDgGgCIgOgFIgKgGQgDgDgCgEQgCgFAAgGQAAgNAIgHQAJgHAQAAQAJAAAGACQAGACAEAEQADADACAEQABAFAAAFIAAADIgXAAIAAgCQAAgFgCgCQgCgDgEAAQgFAAgCADQgCACAAADQAAAFADACIAMAEIAKAEIAIAEQAEADACAFQACAFAAAHQAAANgIAIQgJAIgQAAQgRAAgIgHgAjRgzQgHgEgEgHQgDgGgBgIIgBgUQAAgKABgHQACgIAEgGQAEgFAHgDQAHgEAKAAQALAAAHAEQAHADAEAHQADAGABAJIABAVIgsAAIAAAGQAAAKADAFQABAFAGAAQAFAAACgEQACgEAAgIIAYAAQAAAQgJAIQgIAIgQAAQgMAAgHgEgAi1hoQAAgKgCgEQgBgFgGAAQgGAAgBAFQgDAEAAAKIATAAIAAAAgAl4g2QgGgGAAgOQAAgHADgGQACgGAFgDIAIgDIAKgDIAFgBQAGgCACgBQACgCAAgFQAAgEgCgCQgCgDgFAAQgFAAgCADQgCADAAAGIgXAAQAAgIADgGQACgGAFgDQAEgDAGgBQAGgCAIAAQAQAAAHAGQAIAGAAAOIAAAtIAAALQABAFACACIgZAAIgCgKIAAAAQgDAGgFADQgGAEgGAAQgMAAgFgHgAldhYIgEACQgEADAAAHQAAAFACADQACADADAAQAFAAACgDQADgDAAgGIABgKIAAgFIgKAEgAo2g2QgGgGAAgOQAAgHADgGQADgGAFgDIAHgDIAKgDIAGgBQAGgCABgBQACgCAAgFQAAgEgCgCQgCgDgEAAQgFAAgCADQgCADAAAGIgYAAQABgIACgGQADgGAEgDQAFgDAFgBQAGgCAIAAQARAAAHAGQAHAGAAAOIAAAtIABALQAAAFACACIgZAAIgBgKIgBAAQgCAGgGADQgFAEgHAAQgLAAgGgHgAobhYIgEACQgEADAAAHQAAAFACADQACADAEAAQAEAAADgDQADgDAAgGIAAgKIAAgFIgKAEgAqvg2QgGgGAAgOQAAgHADgGQACgGAFgDIAIgDIAKgDIAFgBQAGgCACgBQACgCAAgFQAAgEgCgCQgCgDgFAAQgFAAgCADQgCADAAAGIgXAAQAAgIADgGQACgGAFgDQAEgDAGgBQAGgCAIAAQAQAAAHAGQAIAGAAAOIAAAtIAAALQABAFACACIgZAAIgCgKIAAAAQgDAGgFADQgGAEgGAAQgMAAgFgHgAqUhYIgEACQgEADAAAHQAAAFACADQACADADAAQAFAAACgDQADgDAAgGIABgKIAAgFIgKAEgAsAg1QgGgGAAgMIAAhBIAaAAIAAA7QAAAKAIAAQAEAAADgDQACgEAAgGIAAg4IAaAAIAABWIgZAAIAAgKIAAAAQgDAGgFADQgGAEgHAAQgLAAgGgGgAwrg2QgGgGAAgOQAAgHADgGQADgGAFgDIAHgDIAKgDIAGgBQAGgCABgBQACgCAAgFQAAgEgCgCQgCgDgEAAQgFAAgCADQgCADAAAGIgYAAQABgIACgGQADgGAEgDQAFgDAFgBQAGgCAIAAQARAAAHAGQAHAGAAAOIAAAtIABALQAAAFACACIgZAAIgBgKIgBAAQgCAGgGADQgFAEgHAAQgLAAgGgHgAwQhYIgEACQgEADAAAHQAAAFACADQACADAEAAQAEAAADgDQADgDAAgGIAAgKIAAgFIgKAEgAx9g6QgGgLAAgXIABgUQABgIADgGQACgGAFgDQAFgEAIAAQAGAAAFADQAFADADAGIABAAIAAglIAaAAIAAByIgZAAIAAgKIgBAAQgBAFgFAEQgFAEgHAAQgOAAgHgLgAxnhyQgCAHAAANIAAALIABAJQABADACACQACADAEAAQAFAAACgHQACgGAAgNQAAgOgCgHQgBgHgGAAQgHAAgBAGgAzsgzQgIgDgDgGQgEgGgBgIIgBgTQAAgKABgJQACgIADgGQAEgGAHgDQAHgEALAAQAMAAAHAEQAHADAEAGQADAGACAIIABATQAAAKgCAIQgBAJgEAGQgEAGgHADQgHAEgLAAQgLAAgHgEgAzhhzQgDAGAAAQQAAAQADAGQACAHAFAAQAGAAACgGQACgGAAgRQAAgRgCgGQgCgGgGAAQgFAAgCAHgA3AgzQgHgEgDgHQgEgGgBgIIgBgUQAAgKACgHQABgIAEgGQAEgFAHgDQAHgEAKAAQAMAAAHAEQAHADADAHQAEAGABAJIABAVIgsAAIAAAGQAAAKACAFQACAFAFAAQAFAAACgEQACgEABgIIAYAAQAAAQgJAIQgJAIgQAAQgLAAgIgEgA2jhoQAAgKgCgEQgCgFgFAAQgGAAgCAFQgCAEAAAKIATAAIAAAAgA6Zg2QgGgGAAgOQAAgHADgGQACgGAFgDIAIgDIAKgDIAFgBQAGgCACgBQACgCAAgFQAAgEgCgCQgCgDgFAAQgFAAgCADQgCADAAAGIgXAAQAAgIADgGQACgGAFgDQAEgDAGgBQAGgCAIAAQAQAAAHAGQAIAGAAAOIAAAtIAAALQABAFACACIgZAAIgCgKIAAAAQgDAGgFADQgGAEgGAAQgMAAgFgHgA5+hYIgEACQgEADAAAHQAAAFACADQACADADAAQAFAAACgDQADgDAAgGIABgKIAAgFIgKAEgA8cg2QgGgGAAgOQAAgHADgGQADgGAFgDIAHgDIAKgDIAGgBQAGgCABgBQACgCAAgFQAAgEgCgCQgCgDgEAAQgFAAgCADQgCADAAAGIgYAAQABgIACgGQADgGAEgDQAFgDAFgBQAGgCAIAAQARAAAHAGQAHAGAAAOIAAAtIABALQAAAFACACIgZAAIgBgKIgBAAQgCAGgGADQgFAEgHAAQgLAAgGgHgA8BhYIgEACQgEADAAAHQAAAFACADQACADAEAAQAEAAADgDQADgDAAgGIAAgKIAAgFIgKAEgEggQgAzQgHgEgEgHQgDgGgBgIIgBgUQAAgKABgHQACgIAEgGQAEgFAHgDQAHgEAKAAQALAAAHAEQAHADAEAHQADAGABAJIABAVIgsAAIAAAGQAAAKADAFQABAFAGAAQAFAAACgEQACgEAAgIIAYAAQAAAQgJAIQgIAIgQAAQgMAAgHgEgA/0hoQAAgKgCgEQgBgFgGAAQgGAAgBAFQgDAEAAAKIATAAIAAAAgEghsgA6QgHgLAAgXIABgUQABgIADgGQADgGAFgDQAFgEAHAAQAHAAAFADQAFADADAGIAAAAIAAglIAaAAIAAByIgZAAIAAgKIAAAAQgCAFgFAEQgEAEgIAAQgNAAgHgLgEghXgByQgCAHAAANIABALIABAJQABADACACQACADADAAQAGAAACgHQACgGAAgNQAAgOgCgHQgCgHgGAAQgGAAgCAGgAC4gyQgEgBgCgCQgDgCgBgFIgBgMIAAguIgLAAIAAgSIALAAIAAgaIAaAAIAAAaIAMAAIAAASIgMAAIAAArQAAAFACACQABABAFAAIAEAAIAAARIgPABIgMgBgAnagyQgEgBgDgCQgCgCgCgFIgBgMIAAguIgKAAIAAgSIAKAAIAAgaIAaAAIAAAaIAMAAIAAASIgMAAIAAArQAAAFACACQACABAFAAIADAAIAAARIgPABIgLgBgA0egyQgEgBgDgCQgCgCgCgFIgBgMIAAguIgKAAIAAgSIAKAAIAAgaIAaAAIAAAaIAMAAIAAASIgMAAIAAArQAAAFACACQACABAFAAIADAAIAAARIgPABIgLgBgA7AgyQgEgBgDgCQgCgCgCgFIgBgMIAAguIgKAAIAAgSIAKAAIAAgaIAaAAIAAAaIAMAAIAAASIgMAAIAAArQAAAFACACQACABAFAAIADAAIAAARIgPABIgLgBgAcZgyIAAg7QAAgKgHAAQgEAAgDADQgDAEAAAGIAAA4IgaAAIAAg7QAAgKgHAAQgEAAgDADQgCAEAAAGIAAA4IgaAAIAAhWIAZAAIAAAKIAAAAQADgGAFgDQAGgEAHAAIAGABIAGACIAFAEIAEAHQAFgIAEgDQAFgDAIAAQALAAAFAGQAGAGAAAMIAABBgAZLgyIAAg7QAAgKgIAAQgEAAgCADQgDAEAAAGIAAA4IgaAAIAAhyIAaAAIAAAlIAAAAQADgGAFgDQAFgDAHAAQALAAAGAGQAGAGAAAMIAABBgASXgyIAAg7QAAgKgHAAQgEAAgDADQgDAEAAAGIAAA4IgaAAIAAhWIAZAAIAAAKIABAAQADgGAFgDQAGgEAHAAQALAAAFAGQAGAGAAAMIAABBgAPhgyIAAhWIAZAAIAAAMIABAAQADgHAFgEQAFgEAIAAIAEABIAAAYIgIgBQgIAAgEAEQgFAEAAAIIAAAxgAM8gyIAAg7QAAgKgIAAQgEAAgCADQgDAEAAAGIAAA4IgaAAIAAg7QAAgKgIAAQgEAAgCADQgDAEAAAGIAAA4IgaAAIAAhWIAZAAIAAAKIABAAQACgGAGgDQAFgEAHAAIAHABIAGACIAFAEIAEAHQAEgIAFgDQAFgDAHAAQALAAAGAGQAGAGAAAMIAABBgAkcgyIgVhWIAbAAIAKBAIALhAIAZAAIgVBWgAm3gyIAAhWIAZAAIAAAMIABAAQADgHAFgEQAFgEAIAAIAEABIAAAYIgIgBQgIAAgEAEQgFAEAAAIIAAAxgAt8gyIgEgWIgcAAIgEAWIgbAAIAdhyIAhAAIAdBygAuEhcIgKgzIAAAAIgKAzIAUAAgA1VgyIAAg7QAAgKgIAAQgEAAgCADQgDAEAAAGIAAA4IgaAAIAAhWIAZAAIAAAKIAAAAQADgGAGgDQAFgEAHAAQALAAAGAGQAGAGAAAMIAABBgA32gyIAAg7QAAgKgIAAQgEAAgCADQgDAEAAAGIAAA4IgaAAIAAg7QAAgKgIAAQgEAAgCADQgDAEAAAGIAAA4IgaAAIAAhWIAZAAIAAAKIABAAQACgGAGgDQAFgEAHAAIAHABIAGACIAFAEIAEAHQAEgIAFgDQAFgDAHAAQALAAAGAGQAGAGAAAMIAABBgA9agyIAAhWIAZAAIAAAMIAAAAQADgHAFgEQAFgEAIAAIAEABIAAAYIgHgBQgIAAgFAEQgEAEAAAIIAAAxgA+VgyIAAhcIgYAAIAAgWIBLAAIAAAWIgYAAIAABcgAjIiRIAIgXIAZAAIgQAXgAuYirIAIgXIAZAAIgQAXgAd/jOIgHgCIgDgBIADgIIAGABIAFABQAEAAACgCQABAAAAgBQAAAAABAAQAAgBAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQgBAAAAAAQAAgBgBAAQgCgCgDAAIgEABIgBAAIgDgDIAHgNQgKgBgGgEQgHgEgDgGIgEgOIAAgTQAAgKABgHQACgIAEgGQAEgFAHgDQAHgEAKAAQAKAAAGADQAHACAEAFQAEAEABAHQACAGAAAIIgYAAQAAgJgCgEQgDgFgFAAQgGAAgCAHQgCAHAAAPQAAAQACAGQACAHAGAAQAGAAACgFQACgEAAgMIAYAAQAAATgHAJQgHAIgQABIgEAIIAEgBQAHAAAEAEQAEADAAAGQAAAGgGAFQgFAEgJAAIgIAAgA0ujXQgGgCgEgDQgEgEgBgEQgCgEAAgFIAYAAQABADACACQACACAEAAQAHAAACgFQACgFAAgMIAAgGIgBAAQgCAHgFADQgGADgHAAQgHAAgFgDQgEgDgDgGQgDgGgBgHIgBgRIAAgRQABgHADgHQADgGAFgEQAFgEAIAAQAIAAAFAEQAFAEACAGIABAAIAAgLIAYAAIAABTQAAAIgCAGQgCAGgEAEQgEAEgHACQgHADgKAAQgJAAgHgCgA0lkyQgCAGAAAMQAAAOADAFQACAFAFAAQAFAAADgFQACgFAAgOQAAgNgCgFQgCgGgGAAQgGAAgCAGgAR6jXIAAhyIAZAAIAAAKIAAAAQACgFAFgEQAEgEAIAAQANAAAHALQAHALAAAXIgBATQgBAJgDAGQgDAGgFADQgFAEgHAAQgHAAgFgDQgFgDgDgGIAAAAIAAAlgASVkyQgCAGAAANQAAAOACAHQACAHAGAAQAGAAACgGQACgHAAgNIgBgLIgBgJQgBgDgCgCQgCgDgDAAQgGAAgCAHgAJNjXIAAhyIAZAAIAAAKIAAAAQACgFAFgEQAEgEAIAAQANAAAHALQAHALAAAXIgBATQgBAJgDAGQgDAGgFADQgFAEgHAAQgHAAgFgDQgFgDgDgGIAAAAIAAAlgAJokyQgCAGAAANQAAAOACAHQACAHAGAAQAGAAACgGQACgHAAgNIgBgLIgBgJQgBgDgCgCQgCgDgDAAQgGAAgCAHgAkhjXIAAhyIAZAAIAAAKIABAAQABgFAFgEQAFgEAHAAQAOAAAHALQAGALAAAXIgBATQgBAJgDAGQgCAGgFADQgFAEgIAAQgGAAgFgDQgFgDgDgGIgBAAIAAAlgAkFkyQgCAGAAANQAAAOACAHQABAHAGAAQAHAAABgGQACgHAAgNIAAgLIgBgJQgBgDgCgCQgCgDgEAAQgFAAgCAHgEAgTgD0QgIgDgDgGQgEgGgBgIIgBgTQAAgKABgJQACgIADgGQAEgGAHgDQAHgEALAAQAMAAAHAEQAHADAEAGQADAGACAIIABATQAAAKgCAIQgBAJgEAGQgEAGgHADQgHAEgLAAQgLAAgHgEgEAgegE0QgDAGAAAQQAAAQADAGQACAHAFAAQAGAAACgGQACgGAAgRQAAgRgCgGQgCgGgGAAQgFAAgCAHgAe4j3QgGgGAAgOQAAgHADgGQACgGAFgDIAIgDIAKgDIAFgBQAGgCACgBQACgCAAgFQAAgEgCgCQgCgDgFAAQgFAAgCADQgCADAAAGIgXAAQAAgIADgGQACgGAFgDQAEgDAGgBQAGgCAIAAQAQAAAHAGQAIAGAAAOIAAAtIAAALQABAFACACIgZAAIgCgKIAAAAQgDAGgFADQgGAEgGAAQgMAAgFgHgAfTkZIgEACQgEADAAAHQAAAFACADQACADADAAQAFAAACgDQADgDAAgGIABgKIAAgFIgKAEgAcbj3QgGgGAAgOQAAgHADgGQACgGAFgDIAIgDIAKgDIAFgBQAGgCACgBQACgCAAgFQAAgEgCgCQgCgDgFAAQgFAAgCADQgCADAAAGIgXAAQAAgIADgGQACgGAFgDQAEgDAGgBQAGgCAIAAQAQAAAHAGQAIAGAAAOIAAAtIAAALQABAFACACIgZAAIgCgKIAAAAQgDAGgFADQgGAEgGAAQgMAAgFgHgAc2kZIgEACQgEADAAAHQAAAFACADQACADADAAQAFAAACgDQADgDAAgGIABgKIAAgFIgKAEgAagj3QgIgGAAgNIAAgEIAXAAQAAAGACAEQACAEAGAAQAEAAACgDQADgCAAgEQAAgEgCgCQgCgDgGgCIgPgFIgJgGQgEgDgCgEQgCgFAAgGQAAgNAJgHQAIgHAQAAQAJAAAGACQAGACAEAEQAEADABAEQACAFAAAFIAAADIgXAAIAAgCQAAgFgCgCQgCgDgFAAQgFAAgCADQgCACAAADQAAAFAEACIALAEIAKAEIAIAEQAEADACAFQADAFAAAHQAAANgJAIQgIAIgQAAQgRAAgIgHgAXVj3QgGgGAAgOQAAgHADgGQACgGAFgDIAIgDIAKgDIAFgBQAGgCACgBQACgCAAgFQAAgEgCgCQgCgDgFAAQgFAAgCADQgCADAAAGIgXAAQAAgIADgGQACgGAFgDQAEgDAGgBQAGgCAIAAQAQAAAHAGQAIAGAAAOIAAAtIAAALQABAFACACIgZAAIgCgKIAAAAQgDAGgFADQgGAEgGAAQgMAAgFgHgAXwkZIgEACQgEADAAAHQAAAFACADQACADADAAQAFAAACgDQADgDAAgGIABgKIAAgFIgKAEgAVbj3QgGgGAAgOQAAgHADgGQADgGAFgDIAHgDIAKgDIAGgBQAGgCABgBQACgCAAgFQAAgEgCgCQgCgDgEAAQgFAAgCADQgCADAAAGIgYAAQABgIACgGQADgGAEgDQAFgDAFgBQAGgCAIAAQARAAAHAGQAHAGAAAOIAAAtIABALQAAAFACACIgZAAIgBgKIgBAAQgCAGgGADQgFAEgHAAQgLAAgGgHgAV2kZIgEACQgEADAAAHQAAAFACADQACADAEAAQAEAAADgDQADgDAAgGIAAgKIAAgFIgKAEgATQj3QgGgGAAgOQAAgHADgGQADgGAFgDIAHgDIAKgDIAGgBQAGgCABgBQACgCAAgFQAAgEgCgCQgCgDgEAAQgFAAgCADQgCADAAAGIgYAAQABgIACgGQADgGAEgDQAFgDAFgBQAGgCAIAAQARAAAHAGQAHAGAAAOIAAAtIABALQAAAFACACIgZAAIgBgKIgBAAQgCAGgGADQgFAEgHAAQgLAAgGgHgATrkZIgEACQgEADAAAHQAAAFACADQACADAEAAQAEAAADgDQADgDAAgGIAAgKIAAgFIgKAEgAQEj3QgGgGAAgOQAAgHADgGQACgGAFgDIAIgDIAKgDIAFgBQAGgCACgBQACgCAAgFQAAgEgCgCQgCgDgFAAQgFAAgCADQgCADAAAGIgXAAQAAgIADgGQACgGAFgDQAEgDAGgBQAGgCAIAAQAQAAAHAGQAIAGAAAOIAAAtIAAALQABAFACACIgZAAIgCgKIAAAAQgDAGgFADQgGAEgGAAQgMAAgFgHgAQfkZIgEACQgEADAAAHQAAAFACADQACADADAAQAFAAACgDQADgDAAgGIABgKIAAgFIgKAEgAOyj7QgHgLAAgXIABgUQABgIADgGQADgGAFgDQAFgEAHAAQAHAAAFADQAFADADAGIAAAAIAAglIAaAAIAAByIgZAAIAAgKIAAAAQgCAFgFAEQgEAEgIAAQgNAAgHgLgAPHkzQgCAHAAANIABALIABAJQABADACACQACADADAAQAGAAACgHQACgGAAgNQAAgOgCgHQgCgHgGAAQgGAAgCAGgANhj3QgGgGAAgOQAAgHADgGQACgGAFgDIAIgDIAKgDIAFgBQAGgCACgBQACgCAAgFQAAgEgCgCQgCgDgFAAQgFAAgCADQgCADAAAGIgXAAQAAgIADgGQACgGAFgDQAEgDAGgBQAGgCAIAAQAQAAAHAGQAIAGAAAOIAAAtIAAALQABAFACACIgZAAIgCgKIAAAAQgDAGgFADQgGAEgGAAQgMAAgFgHgAN8kZIgEACQgEADAAAHQAAAFACADQACADADAAQAFAAACgDQADgDAAgGIABgKIAAgFIgKAEgAKuj0QgHgDgEgGQgDgGgCgIIgBgTQAAgKACgJQABgIAEgGQAEgGAHgDQAHgEALAAQALAAAIAEQAHADADAGQAEAGABAIIABATQAAAKgBAIQgCAJgDAGQgEAGgHADQgHAEgLAAQgMAAgHgEgAK5k0QgCAGAAAQQAAAQACAGQACAHAGAAQAGAAACgGQACgGAAgRQAAgRgCgGQgCgGgGAAQgGAAgCAHgAIIj3QgIgGAAgNIAAgEIAXAAQAAAGACAEQACAEAGAAQAEAAACgDQADgCAAgEQAAgEgCgCQgCgDgGgCIgPgFIgJgGQgEgDgCgEQgCgFAAgGQAAgNAJgHQAIgHAQAAQAJAAAGACQAGACAEAEQAEADABAEQACAFAAAFIAAADIgXAAIAAgCQAAgFgCgCQgCgDgFAAQgFAAgCADQgCACAAADQAAAFAEACIALAEIAKAEIAIAEQAEADACAFQADAFAAAHQAAANgJAIQgIAIgQAAQgRAAgIgHgAFjj3QgGgGAAgOQAAgHADgGQADgGAFgDIAHgDIAKgDIAGgBQAGgCABgBQACgCAAgFQAAgEgCgCQgCgDgEAAQgFAAgCADQgCADAAAGIgYAAQABgIACgGQADgGAEgDQAFgDAFgBQAGgCAIAAQARAAAHAGQAHAGAAAOIAAAtIABALQAAAFACACIgZAAIgBgKIgBAAQgCAGgGADQgFAEgHAAQgLAAgGgHgAF+kZIgEACQgEADAAAHQAAAFACADQACADAEAAQAEAAADgDQADgDAAgGIAAgKIAAgFIgKAEgACJj0QgHgEgDgHQgEgGgBgIIgBgUQAAgKACgHQABgIAEgGQAEgFAHgDQAHgEAKAAQAMAAAHAEQAHADADAHQAEAGABAJIABAVIgsAAIAAAGQAAAKACAFQACAFAFAAQAFAAACgEQACgEABgIIAYAAQAAAQgJAIQgJAIgQAAQgLAAgIgEgACmkpQAAgKgCgEQgCgFgFAAQgGAAgCAFQgCAEAAAKIATAAIAAAAgAAGj3QgGgGAAgOQAAgHADgGQACgGAFgDIAIgDIAKgDIAFgBQAGgCACgBQACgCAAgFQAAgEgCgCQgCgDgFAAQgFAAgCADQgCADAAAGIgXAAQAAgIADgGQACgGAFgDQAEgDAGgBQAGgCAIAAQAQAAAHAGQAIAGAAAOIAAAtIAAALQABAFACACIgZAAIgCgKIAAAAQgDAGgFADQgGAEgGAAQgMAAgFgHgAAhkZIgEACQgEADAAAHQAAAFACADQACADADAAQAFAAACgDQADgDAAgGIABgKIAAgFIgKAEgAhBj3QgIgGAAgNIAAgEIAXAAQABAGABAEQACAEAGAAQAFAAACgDQACgCAAgEQAAgEgCgCQgCgDgGgCIgOgFIgKgGQgDgDgCgEQgCgFAAgGQAAgNAIgHQAJgHAQAAQAJAAAGACQAGACAEAEQADADACAEQABAFAAAFIAAADIgXAAIAAgCQAAgFgCgCQgCgDgEAAQgFAAgCADQgCACAAADQAAAFADACIAMAEIAKAEIAIAEQAEADACAFQACAFAAAHQAAANgIAIQgJAIgQAAQgRAAgIgHgAiFj0QgHgEgEgHQgDgGgBgIIgBgUQAAgKABgHQACgIAEgGQAEgFAHgDQAHgEAKAAQALAAAHAEQAHADAEAHQADAGABAJIABAVIgsAAIAAAGQAAAKADAFQABAFAGAAQAFAAACgEQACgEAAgIIAYAAQAAAQgJAIQgIAIgQAAQgMAAgHgEgAhpkpQAAgKgCgEQgBgFgGAAQgGAAgBAFQgDAEAAAKIATAAIAAAAgAlgj0QgHgEgEgHQgDgGgBgIIgBgUQAAgKABgHQACgIAEgGQAEgFAHgDQAHgEAKAAQALAAAHAEQAHADAEAHQADAGABAJIABAVIgsAAIAAAGQAAAKADAFQABAFAGAAQAFAAACgEQACgEAAgIIAYAAQAAAQgJAIQgIAIgQAAQgMAAgHgEgAlEkpQAAgKgCgEQgBgFgGAAQgGAAgBAFQgDAEAAAKIATAAIAAAAgAofj2QgGgGAAgMIAAhBIAaAAIAAA7QAAAKAHAAQAEAAADgDQADgEAAgGIAAg4IAaAAIAABWIgZAAIAAgKIgBAAQgCAGgGADQgFAEgHAAQgMAAgFgGgApnj0QgHgDgEgGQgDgGgCgIIgBgTQAAgKACgJQABgIAEgGQAEgGAHgDQAHgEALAAQALAAAIAEQAHADADAGQAEAGABAIIABATQAAAKgBAIQgCAJgDAGQgEAGgHADQgHAEgLAAQgMAAgHgEgApck0QgCAGAAAQQAAAQACAGQACAHAGAAQAGAAACgGQACgGAAgRQAAgRgCgGQgCgGgGAAQgGAAgCAHgArgj0QgIgDgDgGQgEgGgBgIIgBgTQAAgKABgJQACgIADgGQAEgGAHgDQAHgEALAAQAMAAAHAEQAHADAEAGQADAGACAIIABATQAAAKgCAIQgBAJgEAGQgEAGgHADQgHAEgLAAQgLAAgHgEgArVk0QgDAGAAAQQAAAQADAGQACAHAFAAQAGAAACgGQACgGAAgRQAAgRgCgGQgCgGgGAAQgFAAgCAHgAu+j0QgIgDgDgGQgEgGgBgIIgBgTQAAgKABgJQACgIADgGQAEgGAHgDQAHgEALAAQAMAAAHAEQAHADAEAGQADAGACAIIABATQAAAKgCAIQgBAJgEAGQgEAGgHADQgHAEgLAAQgLAAgHgEgAuzk0QgDAGAAAQQAAAQADAGQACAHAFAAQAGAAACgGQACgGAAgRQAAgRgCgGQgCgGgGAAQgFAAgCAHgAwbj7QgHgLAAgXIABgUQABgIADgGQADgGAFgDQAFgEAHAAQAHAAAFADQAFADADAGIAAAAIAAglIAaAAIAAByIgZAAIAAgKIAAAAQgCAFgFAEQgEAEgIAAQgNAAgHgLgAwGkzQgCAHAAANIABALIABAJQABADACACQACADADAAQAGAAACgHQACgGAAgNQAAgOgCgHQgCgHgGAAQgGAAgCAGgAyWj3QgGgGAAgOQAAgHADgGQADgGAFgDIAHgDIAKgDIAGgBQAGgCABgBQACgCAAgFQAAgEgCgCQgCgDgEAAQgFAAgCADQgCADAAAGIgYAAQABgIACgGQADgGAEgDQAFgDAFgBQAGgCAIAAQARAAAHAGQAHAGAAAOIAAAtIABALQAAAFACACIgZAAIgBgKIgBAAQgCAGgGADQgFAEgHAAQgLAAgGgHgAx7kZIgEACQgEADAAAHQAAAFACADQACADAEAAQAEAAADgDQADgDAAgGIAAgKIAAgFIgKAEgAzmj2QgGgGAAgMIAAhBIAaAAIAAA7QAAAKAHAAQAEAAADgDQADgEAAgGIAAg4IAaAAIAABWIgZAAIAAgKIgBAAQgCAGgGADQgFAEgHAAQgMAAgFgGgA2Mj3QgGgGAAgOQAAgHADgGQADgGAFgDIAHgDIAKgDIAGgBQAGgCABgBQACgCAAgFQAAgEgCgCQgCgDgEAAQgFAAgCADQgCADAAAGIgYAAQABgIACgGQADgGAEgDQAFgDAFgBQAGgCAIAAQARAAAHAGQAHAGAAAOIAAAtIABALQAAAFACACIgZAAIgBgKIgBAAQgCAGgGADQgFAEgHAAQgLAAgGgHgA1xkZIgEACQgEADAAAHQAAAFACADQACADAEAAQAEAAADgDQADgDAAgGIAAgKIAAgFIgKAEgA4Fj3QgGgGAAgOQAAgHADgGQACgGAFgDIAIgDIAKgDIAFgBQAGgCACgBQACgCAAgFQAAgEgCgCQgCgDgFAAQgFAAgCADQgCADAAAGIgXAAQAAgIADgGQACgGAFgDQAEgDAGgBQAGgCAIAAQAQAAAHAGQAIAGAAAOIAAAtIAAALQABAFACACIgZAAIgCgKIAAAAQgDAGgFADQgGAEgGAAQgMAAgFgHgA3qkZIgEACQgEADAAAHQAAAFACADQACADADAAQAFAAACgDQADgDAAgGIABgKIAAgFIgKAEgA50j0QgHgDgEgGQgDgGgCgIIgBgTQAAgKACgJQABgIAEgGQAEgGAHgDQAHgEALAAQALAAAIAEQAHADADAGQAEAGABAIIABATQAAAKgBAIQgCAJgDAGQgEAGgHADQgHAEgLAAQgMAAgHgEgA5pk0QgCAGAAAQQAAAQACAGQACAHAGAAQAGAAACgGQACgGAAgRQAAgRgCgGQgCgGgGAAQgGAAgCAHgA8mj0QgHgEgEgHQgDgGgBgIIgBgUQAAgKABgHQACgIAEgGQAEgFAHgDQAHgEAKAAQALAAAHAEQAHADAEAHQADAGABAJIABAVIgsAAIAAAGQAAAKADAFQABAFAGAAQAFAAACgEQACgEAAgIIAYAAQAAAQgJAIQgIAIgQAAQgMAAgHgEgA8KkpQAAgKgCgEQgBgFgGAAQgGAAgBAFQgDAEAAAKIATAAIAAAAgAb0jzQgEgBgDgCQgCgCgCgFIgBgMIAAguIgKAAIAAgSIAKAAIAAgaIAaAAIAAAaIAMAAIAAASIgMAAIAAArQAAAFACACQACABAFAAIADAAIAAARIgPABIgLgBgAM6jzQgEgBgDgCQgCgCgCgFIgBgMIAAguIgKAAIAAgSIAKAAIAAgaIAaAAIAAAaIAMAAIAAASIgMAAIAAArQAAAFACACQACABAFAAIADAAIAAARIgPABIgLgBgAEBjzQgEgBgCgCQgDgCgBgFIgBgMIAAguIgLAAIAAgSIALAAIAAgaIAaAAIAAAaIAMAAIAAASIgMAAIAAArQAAAFACACQABABAFAAIAEAAIAAARIgPABIgMgBgAZMjzIAAhyIBCAAIAAAWIgnAAIAAAXIAlAAIAAAVIglAAIAAAaIApAAIAAAWgAUdjzIAAhWIAZAAIAAAMIAAAAQADgHAFgEQAFgEAIAAIAEABIAAAYIgHgBQgIAAgFAEQgEAEAAAIIAAAxgALwjzIAAhWIAZAAIAAAMIAAAAQADgHAFgEQAFgEAIAAIAEABIAAAYIgHgBQgIAAgFAEQgEAEAAAIIAAAxgAHbjzIAAg7QAAgKgIAAQgEAAgCADQgDAEAAAGIAAA4IgaAAIAAhWIAZAAIAAAKIAAAAQADgGAGgDQAFgEAHAAQALAAAGAGQAGAGAAAMIAABBgAEljzIAAhWIAZAAIAAAMIAAAAQADgHAFgEQAFgEAIAAIAEABIAAAYIgHgBQgIAAgFAEQgEAEAAAIIAAAxgAjOjzIAAhWIAZAAIAAAMIABAAQADgHAFgEQAFgEAIAAIAEABIAAAYIgIgBQgIAAgEAEQgFAEAAAIIAAAxgAmpjzIAAhWIAZAAIAAAMIABAAQADgHAFgEQAFgEAIAAIAEABIAAAYIgIgBQgIAAgEAEQgFAEAAAIIAAAxgAsXjzIAAhWIAaAAIAABWgAtTjzIAAhWIAZAAIAAAMIAAAAQADgHAFgEQAFgEAIAAIAEABIAAAYIgHgBQgIAAgFAEQgEAEAAAIIAAAxgA69jzIAAhWIAZAAIAAAMIAAAAQADgHAFgEQAFgEAIAAIAEABIAAAYIgHgBQgIAAgFAEQgEAEAAAIIAAAxgA7mjzIAAhWIAaAAIAABWgA9djzIAAg7QAAgKgHAAQgEAAgDADQgDAEAAAGIAAA4IgaAAIAAg7QAAgKgHAAQgEAAgDADQgCAEAAAGIAAA4IgaAAIAAhWIAZAAIAAAKIAAAAQADgGAFgDQAGgEAHAAIAGABIAGACIAFAEIAEAHQAFgIAEgDQAFgDAIAAQALAAAFAGQAGAGAAAMIAABBgA/cjzIAAhWIAaAAIAABWgEggYgDzIAAhWIAZAAIAAAMIABAAQADgHAFgEQAFgEAIAAIAEABIAAAYIgIgBQgIAAgEAEQgFAEAAAIIAAAxgEghvgDzIAAhyIApAAQAKAAAHADQAHADADAGQAEAFACAGIABAMQAAAQgJAJQgIAKgUAAIgMAAIAAAsgEghVgEzIAIAAQAHAAADgEQADgEAAgHQAAgHgDgEQgDgEgIAAIgHAAgACTlSIAHgXIAZAAIgQAXgAsXlSIAAgUIAaAAIAAAUgA14lSIAIgXIAZAAIgQAXgA7mlSIAAgUIAaAAIAAAUgA/clSIAAgUIAaAAIAAAUgAfZlUIgGgCIgHgCQAAAAgBAAQAAAAgBABQAAAAAAAAQgBAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAQAAABAAAAIgNAAQABgKAEgFQAEgHAGAAQAFAAAGADIADAAIAFACIAEgBIABgEIANAAIgBAIIgDAHQgCADgDACQgDACgEAAIgGgBg");
	this.shape.setTransform(36,6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000033").s().p("AAUEkIAAm/Ih2BMIAAhMQAugWA0gpQAvgmAbgjIAZAAIAAJHg");
	this.shape_1.setTransform(-218.6,-3.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF9900").s().rr(-263,-60.5,526,121,25.5);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-262.9,-60.5,526,121);


(lib._1_Interpolação1 = function() {
	this.initialize();

	// Camada 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#466969").s().p("AgwAxQgVgVAAgcQAAgcAVgUQAUgVAcAAQAcAAAVAVQAUAUABAcQgBAcgUAVQgVAUgcABQgcgBgUgUg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-7,-7,14,14);


(lib._1_Interpolacao1cópia3 = function() {
	this.initialize();

	// Camada 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#66CCCC").s().p("AqdgzIHwhyINLDWInvB1g");
	this.shape.setTransform(8.1,6.9);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-58.9,-9.7,134.2,33.3);


(lib._1_Interpolacao1cópia2 = function() {
	this.initialize();

	// Camada 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(102,255,204,0.576)").s().p("AuSAEIQRj5IMTDhIwVEKg");
	this.shape.setTransform(91.2,-20.9);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-0.3,-45.5,183,49.3);


(lib._1_Interpolacao1cópia = function() {
	this.initialize();

	// Camada 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(102,255,204,0.576)").s().p("ApTAOILAilIHnCKIqUClg");
	this.shape.setTransform(0.7,0.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-58.9,-15,119.3,30.5);


(lib._1_Interpolacao1 = function() {
	this.initialize();

	// Camada 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#66CCCC").s().p("AofADIIfiPIIgCOIosCLg");
	this.shape.setTransform(-4.5,1.3);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-58.9,-12.8,108.9,28.3);


(lib._1_Símbolo5 = function() {
	this.initialize();

	// Camada 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.576)").s().rr(-3,-1.15,6,2.3,1.15);
	this.shape.setTransform(221.2,50.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0.576)").s().rr(-4,-1.9,8,3.8,1.9);
	this.shape_1.setTransform(211.7,48.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(0,255,204,0.576)").s().rr(-2.25,-1,4.5,2,1);
	this.shape_2.setTransform(253.9,49);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(255,255,255,0.576)").s().rr(-2.25,-1,4.5,2,1);
	this.shape_3.setTransform(243.9,38.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(255,255,255,0.576)").s().rr(-3,-1.15,6,2.3,1.15);
	this.shape_4.setTransform(259.1,40.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(255,255,255,0.576)").s().rr(-2.25,-1,4.5,2,1);
	this.shape_5.setTransform(264.3,38.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(255,255,255,0.576)").s().rr(-4,-1.9,8,3.8,1.9);
	this.shape_6.setTransform(257.1,35.5);

	this.instance = new lib._1_Interpolacao1cópia3("synched",0);
	this.instance.setTransform(211.6,48.1,0.446,0.488);
	this.instance.alpha = 0.68;

	this.instance_1 = new lib._1_Interpolacao1cópia2("synched",0);
	this.instance_1.setTransform(217,50.3,0.45,0.454,0,-8.1,0);
	this.instance_1.alpha = 0.82;

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("rgba(255,255,255,0.576)").s().rr(-2.25,-1,4.5,2,1);
	this.shape_7.setTransform(305.3,75.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("rgba(255,255,255,0.576)").s().rr(-3,-1.15,6,2.3,1.15);
	this.shape_8.setTransform(320.6,76.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("rgba(255,255,255,0.576)").s().rr(-2.25,-1,4.5,2,1);
	this.shape_9.setTransform(325.8,74.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("rgba(255,255,255,0.576)").s().rr(-4,-1.9,8,3.8,1.9);
	this.shape_10.setTransform(318.6,71.7);

	this.instance_2 = new lib._1_Interpolacao1("synched",0);
	this.instance_2.setTransform(318.6,73.4,0.446,0.488);
	this.instance_2.alpha = 0.68;

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("rgba(255,255,255,0.576)").s().rr(-3,-1.15,6,2.3,1.15);
	this.shape_11.setTransform(157.6,82.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("rgba(255,255,255,0.576)").s().rr(-2.25,-1,4.5,2,1);
	this.shape_12.setTransform(149.9,75.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("rgba(255,255,255,0.576)").s().rr(-4,-1.9,8,3.8,1.9);
	this.shape_13.setTransform(148.1,80);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("rgba(255,255,255,0.576)").s().rr(-3,-1.15,6,2.3,1.15);
	this.shape_14.setTransform(78.5,52.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("rgba(255,255,255,0.576)").s().rr(-2.25,-1,4.5,2,1);
	this.shape_15.setTransform(69.3,50.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("rgba(255,255,255,0.576)").s().rr(-4,-1.9,8,3.8,1.9);
	this.shape_16.setTransform(76.5,48.1);

	this.instance_3 = new lib._1_Interpolacao1cópia("synched",0);
	this.instance_3.setTransform(37.3,38.8,0.45,0.454,0,-8.1,0);
	this.instance_3.alpha = 0.488;

	this.instance_4 = new lib._1_Interpolacao1("synched",0);
	this.instance_4.setTransform(155.6,79.1,0.446,0.488);
	this.instance_4.alpha = 0.68;

	this.instance_5 = new lib._1_Interpolacao1("synched",0);
	this.instance_5.setTransform(77.2,49.8,0.488,0.488);
	this.instance_5.alpha = 0.488;

	this.instance_6 = new lib._1_Símbolo2();
	this.instance_6.setTransform(299.7,70.5,0.529,0.529,0,0,0,566.8,112.5);

	this.addChild(this.instance_6,this.instance_5,this.instance_4,this.instance_3,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.instance_2,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.instance_1,this.instance,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,479.8,400.6);


(lib._1_sujo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada 1
	this.instance = new lib._1_Interpolação1("synched",0);
	this.instance.setTransform(7,7);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:209,y:80},24).to({x:215,y:64},4).to({x:317,y:104},16).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,14,14);


(lib._1_processo = function() {
	this.initialize();

	// Camada 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF9900").s().p("AjbEcIAAo3IG3AAIAAI3g");
	this.shape.setTransform(131,212.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(123,247,247,0.408)").s().p("Al0ImIAAxLILpAAIAARLg");
	this.shape_1.setTransform(67.3,116);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgLAoIh2g1IAdg/IB0A3IAWgvIBdCDIifAOg");
	this.shape_2.setTransform(213.1,86.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgDAoIiDAAIAAhDICCAAIAAg0ICLBPIiKBRg");
	this.shape_3.setTransform(285.1,103.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgDAoIiDAAIAAhDICDAAIgBg0ICKBPIiJBRg");
	this.shape_4.setTransform(350.9,103.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#CCCCCC").s().p("AgZBrIAAjVIA0AAIAADVg");
	this.shape_5.setTransform(123.4,42.3);

	this.instance = new lib._1_sujo();
	this.instance.setTransform(127.1,46.5,0.598,0.598,0,0,0,7,7.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#466969").s().p("AgnF4QgKgKAAgPQAAgPAKgKQALgLAPAAQANAAAKALQALAKAAAPQAAAPgLAKQgKALgNAAQgPAAgLgLgAgxDbQgMgMAAgRQAAgSAMgMQAMgMASAAQARAAAKAMQANAMAAASQAAARgNAMQgKAMgRAAQgSAAgMgMgAgqBsQgHgHAAgKQAAgKAHgHQAHgHAKAAQAKAAAGAHQAIAHAAAKQAAAKgIAHQgGAHgKAAQgKAAgHgHgAgHA3QgMgNAAgRQAAgRAMgLQAKgMASAAQARAAAMAMQAMALAAARQAAARgMANQgMAMgRAAQgSAAgKgMgAgxg/QgMgMAAgSQAAgRAMgMQAMgMASAAQARAAAKAMQANAMAAARQAAASgNAMQgKAMgRAAQgSAAgMgMgAgSiTQgHgHAAgKQAAgKAHgHQAGgHALAAQAIAAAGAHQAIAHAAAKQAAAKgIAHQgGAHgIAAQgLAAgGgHgAgMlZQgHgHAAgKQAAgKAHgGQAGgIAJAAQAJAAAHAIQAIAGAAAKQAAAKgIAHQgHAHgJAAQgJAAgGgHg");
	this.shape_6.setTransform(312.9,114.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#466969").s().p("ABZEiQgRgSAAgZQAAgYARgSQASgRAYAAQAaAAARARQASASAAAYQAAAZgSASQgRARgaAAQgYAAgSgRgAjkEIQgUgTABgbQgBgcAUgTQATgTAbAAQAcAAASATQAUATAAAcQAAAbgUATQgSATgcAAQgbAAgTgTgAB5BSQgWgWAAgfQAAgdAWgWQAVgWAgAAQAeAAAXAWQAVAWAAAdQAAAfgVAWQgXAWgeAAQggAAgVgWgACXjSQgQgQgBgYQABgXAQgRQARgQAYAAQAXAAAQAQQARARAAAXQAAAYgRAQQgQARgXAAQgYAAgRgRg");
	this.shape_7.setTransform(228.1,125.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#666666").ss(1,1,1).p("AAToKIAVAAIAAAwIAABIIAAA8IAAA7IAAA8IAAA8IAAA8IAAA8IAAA5IAAA8IAAA8IAAA8IAAA8IAAA7IAAA8IAAA8IAAA8IAAAeIgVAAIgTAAIAAgeIATAAIAVAAAATnaIAVAAAATnaIAAgwAAAnaIAAgwIATAAAAAnaIATAAAgnnaIAAgwIASAAIAVAAAgnnaIASAAIAAgwAgnlWIAAg8IASAAIAAhIIAVAAAgnlWIASAAIAAg8IAVAAIATAAIAVAAAAAlWIAAg8IAAhIAATlWIAVAAAATlWIAAg8IAAhIAAAlWIATAAAgnmSIAAhIAgVlWIAVAAAAAkbIATAAIAAg7AAAjfIATAAIAAg8IAVAAAAAjfIAAg8IAAg7AATjfIAVAAAgnjfIASAAIAAg8IAVAAAgnkbIASAAIAAg7AgnjfIAAg8IAAg7AgnhnIASAAIAAg8IAAg8IAVAAAgnhnIAAg8IASAAIAVAAIATAAIAVAAAAThnIAVAAAAThnIAAg8IAAg8AAAhnIAAg8IAAg8AAAhnIATAAAgnijIAAg8AgVhnIAVAAAAAgrIATAAIAVAAAAAAOIAAg5IAAg8AATAOIAAg5IAAg8AAAAOIATAAAAABKIATAAIAAg8IAVAAAAABKIAAg8AATBKIAVAAAgnBKIAAg8IASAAIAAg5IAVAAAgVBKIAAg8IAVAAAgnBKIASAAIAVAAAgnAOIAAg5IASAAIAAg8AgnDCIAAg8IASAAIAAg8AgVDCIAAg8IAVAAIATAAIAAg8AgnDCIASAAIAVAAIAAg8IAAg8AATDCIAAg8IAVAAAATDCIAVAAAAADCIATAAAgnCGIAAg8AAAD+IATAAIAVAAAAAE5IATAAIAAg7IAAg8AAAE5IAAg7IAAg8AATE5IAVAAAgVE5IAAg7IAVAAAgnE5IAAg7IASAAIAAg8AgnE5IASAAIAVAAAgnGxIASAAIAAg8IAAg8AgnGxIAAg8IASAAIAVAAIATAAIAVAAAAAGxIAAg8IAAg8AATGxIAAg8IAAg8AATGxIAVAAAAAGxIATAAAgVGxIAVAAAgnF1IAAg8AgnD+IAAg8AATILIAAgeIAAg8AgVILIgSAAIAAgeIASAAIAVAAIAAg8AgVILIAAgeIAAg8AAAILIgVAAAgnHtIAAg8AgngrIAAg8");
	this.shape_8.setTransform(316,103.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#666666").ss(1,1,1).p("AAToKIAVAAIAAAwIAABIIAAA8IAAA7IAAA8IAAA8IAAA8IAAA8IAAA5IAAA8IAAA8IAAA8IAAA8IAAA7IAAA8IAAA8IAAA8AATnaIAAgwAATnaIAVAAAgnnaIAAgwIASAAIAVAAIATAAAAAnaIAAgwAgVnaIAAgwAgVnaIAVAAIATAAAgnnaIASAAAAAlWIAAg8IAAhIAgVlWIAAg8IAVAAIATAAIAVAAAgnlWIAAg8IASAAIAAhIAgVlWIAVAAIATAAIAAg8IAAhIAgnlWIASAAAATlWIAVAAAgnmSIAAhIAATkbIAVAAAATjfIAVAAAATjfIAAg8IAAg7AgnjfIASAAIAAg8IAVAAIATAAAgVjfIAVAAIAAg8IAAg7AgnjfIAAg8IASAAIAAg7AgnhnIAAg8IASAAIAVAAIATAAIAVAAAAAhnIAAg8IAAg8IATAAAgVhnIAAg8IAAg8AgVhnIAVAAIATAAIAAg8IAAg8AgnhnIASAAAAThnIAVAAAgnijIAAg8AgnkbIAAg7AATBKIAAg8IAAg5IAVAAAATBKIAVAAAATAOIAVAAAgVgrIAVAAIATAAIAAg8AgVAOIAVAAIAAg5IAAg8AgVAOIAAg5IAAg8AgnAOIAAg5IASAAAgVBKIAVAAIAAg8IATAAAgVBKIAAg8AgnBKIASAAAgnAOIASAAAgnBKIAAg8AgnDCIASAAIAVAAIAAg8IATAAIAVAAAgnDCIAAg8IASAAIAVAAIAAg8IATAAAgVDCIAAg8IAAg8AATDCIAVAAAATDCIAAg8IAAg8AAADCIATAAAgnCGIAAg8AATD+IAVAAAATE5IAVAAAATE5IAAg7IAAg8AgnE5IASAAIAVAAIAAg7IATAAAgVD+IAVAAIAAg8AgnE5IAAg7IASAAIAAg8AgVE5IAAg7AgnGxIASAAIAVAAIAAg8IATAAIAVAAAgVGxIAAg8IAVAAIAAg8IATAAAgnGxIAAg8IASAAIAAg8AATGxIAVAAAATGxIAAg8IAAg8AAAGxIATAAAgnF1IAAg8AgnD+IAAg8AATHtIAVAAIAAAeIgVAAIAAgeIAAg8AgVHtIAVAAIATAAAAAILIgVAAIAAgeIAAg8AAAILIAAgeIAAg8AgVILIgSAAIAAgeIASAAAATILIgTAAAgnHtIAAg8AgngrIAAg8");
	this.shape_9.setTransform(251.4,103.5);

	this.instance_1 = new lib._1_jato();
	this.instance_1.setTransform(175.6,69.1,0.598,0.598,0,0,0,86.7,46.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#666666").s().p("A2IL0IAAyqIAAi/IAAh+ICbAAIAAFnIAXAkIJSPMIdlAAIAAnGICoAAIAAJWgAThglIAAlDIAAmLICoAAIAALOg");
	this.shape_10.setTransform(246.9,95.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#66CCCC").s().p("Au0HnIpSvNMAm3AAAIAAFDIgFAAIAAAkII4AAIAkAAIAACCIgkAAIo4AAIAAAeIAFAAIAAHGg");
	this.shape_11.setTransform(277.3,107.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#CCCCCC").s().p("A+BK4IAAifIDdAAIAAuHIABAAIAAifQADicCSgOID1AAIAAC/IjdAAIAAQ/IgDAAQgSBmiBALgAX4BdIioAAIgGAAIAAgeII4AAIAAAegAVKhDIAAgkIAGAAICoAAIGKAAIAAAkg");
	this.shape_12.setTransform(235.8,101.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FF9900").s().rr(-223,-105,446,210,25.5);
	this.shape_13.setTransform(223,105);

	this.addChild(this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.instance_1,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.instance,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,446,241);


// stage content:



(lib.tela1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_61 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(61).call(this.frame_61).wait(1));

	// processo
	this.instance = new lib._1_processo();
	this.instance.setTransform(553,148.5,1,1,0,0,0,223,120.5);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(46).to({_off:false},0).to({alpha:1},15).wait(1));

	// texto
	this.instance_1 = new lib._1_Interpolação2("synched",0);
	this.instance_1.setTransform(306,314.5);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(22).to({_off:false},0).to({alpha:1},4).wait(36));

	// Camada 5
	this.instance_2 = new lib._1_Interpolação4("synched",0);
	this.instance_2.setTransform(516.2,360.9);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(14).to({_off:false},0).to({alpha:1},3).wait(45));

	// Camada 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,0,0,0.639)").s().p("EAvfAszQgQgjAAgyMAAAgmVQhrgGhIgVIgJgDQhUgagkgWQgLgHgHgHIhxmPIgEgVQBLhhDbhTIAAAAIABgDQAKgVBHgPQBSgRB1AAQBzAABTARQBGAPALAUQDKBOBHBTQAEAEADAFIABACQAEAHAAAIQAAAIgEAHIgBACIgoCiIA6AAIAAwrIj+ABIAABBIAAADQAAAlhYAbIgUAFQhrAdiZAAIgiAAQhfgChNgOIgcgGIgagHIgHgBQhjgdgCgmIAAu0IiFgZIgCN6QADA1hvguIh1ghIAAgBIlrhkIlSBXIn4iDIAAjAIH3iCIGWBpIE1hUIq3jKQhIgHglAJIAAhCIACAAQATgCAWAAQATAAATADIAbAEIARADIK2DHQBfAYAGAbQAHAZhMAdIkCBVIAACrIgJACIisguQgrAMgIAXIgBAIIABgFQAHgWAsgNIF7BmIAAgEICPAmIAAtsIAUgPIDFAfIAAiMQABgEABgEQAIgdA6geIEzi3IFcDgIAGAHQAHAJAAAKIAAABIAAABIAAPeIEuAAIAIgBQAZAAAQARQAQAQABAYIAASaQgBAXgQARIgBACIAAAPIi6AAIAAAAIgUBSIAAAEIAAABQAAAKgRAVQgSAUh3AgQg1AOhFAIQhLAJhdADIggAAIgJABMAAAAmSQAAAygRAjQgRAigYAAQgXAAgRgigAvSyWIAAjBIBWgWIkAhCIlyBfIlAhTIi+g8IgBAAIm6k/QpSChsLC5IAA2QMAgoAAAUAmlACAgoYAMLIErBNIA2gOIJFCXIAAELIhSAXID6BEIEmhMID6BCIBOgQIhZgbIABkqISbkoIKFC3IAAErIx8E3InCiDIg3AQIBaAXIAADBIn1CCgEggNgb9IAIgCIgRgEg");
	this.shape.setTransform(-475,-56.9);

	this.instance_3 = new lib._1_Símbolo5();
	this.instance_3.setTransform(452.2,361.3,1.325,1.325,0,0,0,240.6,200.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0.576)").s().rr(-4,-1.9,8,3.8,1.9);
	this.shape_1.setTransform(223.4,98.2,1.35,1.35,0,0,0,-0.1,0.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(255,255,255,0.576)").s().rr(-3,-1.15,6,2.3,1.15);
	this.shape_2.setTransform(180.4,107.5,2.228,2.228);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(255,255,255,0.576)").s().rr(-4,-1.9,8,3.8,1.9);
	this.shape_3.setTransform(175.6,97.3,2.228,2.228);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#66CCCC").s().p("Au5mbIS4AAUAc/ABggv3ALXg");
	this.shape_4.setTransform(262.7,115,1.726,1.726,0,0,0,56.7,-1.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.instance_3},{t:this.shape}]}).wait(62));

	// Camada 6
	this.instance_4 = new lib._1_Interpolação3("synched",0);
	this.instance_4.setTransform(382.9,198);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(14).to({_off:false},0).to({alpha:1},3).wait(45));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-465.6,-155.5,1628.8,973.3);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;